export const fallbackDoctors = [
  {
    name: "Dr. Amardeep Yadav",
    specialty: "HPB Surgery & Liver Transplantation",
    specialties: ["HPB Surgery", "Liver Transplantation"],
    experience: "23 years",
    experience_years: 23,
    hospital: "Shalby Hospital Gurugram",
    rating: 4.9,
    slug: "dr-amardeep-yadav",
    photo_url: "https://satyughealthcare.com/uploads/doctors/a330cd2834d5826c649d5295bc0cfae7.jpg",
    qualifications: "MBBS, MS, Fellowship in HPB Surgery & Liver Transplant",
    about:
      "Senior Liver Transplant and HPB Surgeon at Shalby Gurugram with 23 years of experience in hepatobiliary and pancreatic surgery, living donor liver transplants, and complex hepatic resections.",
  },
  {
    name: "Prof (Dr) Deepak Sreevastava",
    specialty: "Anesthesiology",
    specialties: ["Anesthesiology", "Pain Management"],
    experience: "25 years",
    experience_years: 25,
    hospital: "Marengo Asia Hospitals Gurugram",
    rating: 4.8,
    slug: "prof-dr-deepak-sreevastava",
    photo_url: "https://satyughealthcare.com/uploads/doctors/83f330c1455c85f02e5999ff117ea28c.png",
    qualifications: "MBBS, MD - Anaesthesiology, Fellowship in Pain Management",
    about:
      "Senior Anaesthesiologist at Marengo Asia Hospitals Gurugram with 25 years of experience specializing in critical care anaesthesia, regional anaesthesia, and chronic pain management.",
  },
  {
    name: "Parul Yadav",
    specialty: "Nutrition & Dietetics",
    specialties: ["Nutrition", "Dietetics"],
    experience: "10 years",
    experience_years: 10,
    hospital: "Marengo Asia Hospitals Gurugram",
    rating: 4.7,
    slug: "parul-yadav",
    photo_url: "https://satyughealthcare.com/uploads/doctors/02d0523dfc0fa31c2dd37bd96ed16471.jpg",
    qualifications: "MSc in Clinical Nutrition / Dietetics",
    about:
      "Nutrition and Dietetics Specialist at Marengo Asia Hospitals Gurugram with 10 years of experience in clinical nutrition, therapeutic diets, and lifestyle disease management.",
  },
  {
    name: "Dr. Yogendra Singh Rajput",
    specialty: "Cardiology",
    specialties: ["Cardiology", "Internal Medicine"],
    experience: "16 years",
    experience_years: 16,
    hospital: "Delhi NCR",
    rating: 4.8,
    slug: "dr-yogendra-singh-rajput",
    photo_url: "https://satyughealthcare.com/uploads/doctors/492147103510.jpg",
    qualifications: "MBBS, MD - Internal Medicine, DM - Cardiology",
    about:
      "Interventional Cardiologist with 16 years of experience specializing in coronary angioplasty, cardiac catheterization, and management of complex cardiac conditions.",
  },
  {
    name: "Dr. Vishal Gurnani",
    specialty: "Orthopaedics",
    specialties: ["Orthopaedics", "Paediatric Orthopaedics"],
    experience: "8 years",
    experience_years: 8,
    hospital: "Delhi NCR",
    rating: 4.7,
    slug: "dr-vishal-gurnani",
    photo_url: "https://satyughealthcare.com/uploads/doctors/492147103510.jpg",
    qualifications: "MBBS, MS - Orthopaedics, Fellowship in Paediatric Orthopaedics",
    about:
      "Orthopaedic surgeon with 8 years of experience specializing in paediatric orthopaedics, joint disorders in children, and musculoskeletal deformity correction.",
  },
  {
    name: "Dr. Vikas Sharma",
    specialty: "Neurology",
    specialties: ["Neurology", "Internal Medicine"],
    experience: "17 years",
    experience_years: 17,
    hospital: "Delhi NCR",
    rating: 4.8,
    slug: "dr-vikas-sharma",
    photo_url: "https://satyughealthcare.com/uploads/doctors/811031731733.jpg",
    qualifications: "MBBS, MD - Internal Medicine (Maulana Azad Medical College, New Delhi), DM - Neurology (PGIMER Chandigarh)",
    about:
      "Senior Neurologist with 17 years of experience trained at MAMC Delhi and PGIMER Chandigarh, specializing in stroke management, epilepsy, movement disorders, and neuromuscular diseases.",
  },
  {
    name: "Dr. Siddhartha Gogia",
    specialty: "Paediatrics & Neonatology",
    specialties: ["Paediatrics", "Neonatology"],
    experience: "15 years",
    experience_years: 15,
    hospital: "Delhi NCR",
    rating: 4.8,
    slug: "dr-siddhartha-gogia",
    photo_url: "https://satyughealthcare.com/uploads/doctors/161501531397.jpg",
    qualifications: "MBBS, MD - Paediatrics, Fellowship in Neonatology",
    about:
      "Paediatrician and Neonatologist with 15 years of experience specializing in newborn intensive care, premature infant management, and paediatric critical care.",
  },
  {
    name: "Dr. Shilpi Budhiraja",
    specialty: "ENT (Ear, Nose & Throat)",
    specialties: ["ENT"],
    experience: "14 years",
    experience_years: 14,
    hospital: "Delhi NCR",
    rating: 4.7,
    slug: "dr-shilpi-budhiraja",
    photo_url: "https://satyughealthcare.com/uploads/doctors/325417863181.jpg",
    qualifications: "MBBS, MS - ENT",
    about:
      "ENT Specialist with 14 years of experience in ear, nose, and throat disorders, including endoscopic sinus surgery, tonsillectomy, and hearing loss management.",
  },
  {
    name: "Dr. Shilpa Jaiswal",
    specialty: "Neurology",
    specialties: ["Neurology", "Internal Medicine"],
    experience: "10 years",
    experience_years: 10,
    hospital: "Delhi NCR",
    rating: 4.7,
    slug: "dr-shilpa-jaiswal",
    photo_url: "https://satyughealthcare.com/uploads/doctors/811031731733.jpg",
    qualifications: "MBBS (King George's Medical University), MD - Internal Medicine (KGMU), DM - Neurology",
    about:
      "Neurologist with 10 years of experience trained at King George's Medical University, specializing in stroke, epilepsy, headache disorders, and neurodegenerative diseases.",
  },
  {
    name: "Dr. Shallini Mittal",
    specialty: "Radiology",
    specialties: ["Radiology"],
    experience: "12 years",
    experience_years: 12,
    hospital: "Delhi NCR",
    rating: 4.7,
    slug: "dr-shallini-mittal",
    photo_url: "https://satyughealthcare.com/uploads/doctors/617264631571.png",
    qualifications: "MBBS, MD - Radiology",
    about:
      "Radiologist with 12 years of experience specializing in diagnostic and interventional radiology, CT scans, MRI imaging, and image-guided procedures.",
  },
  {
    name: "Dr. Sanket Goyal",
    specialty: "Paediatrics & Neonatology",
    specialties: ["Paediatrics", "Neonatology"],
    experience: "10 years",
    experience_years: 10,
    hospital: "Delhi NCR",
    rating: 4.7,
    slug: "dr-sanket-goyal",
    photo_url: "https://satyughealthcare.com/uploads/doctors/161501531397.jpg",
    qualifications: "MBBS (Saurashtra University, Gujarat, 2010), DNB - Paediatrics (National Board of Examination, India, 2014), Fellowship in Neonatology",
    about:
      "Paediatrician and Neonatologist with 10 years of experience specializing in neonatal intensive care, preterm baby management, and paediatric infectious diseases.",
  },
  {
    name: "Dr. Sanjeev Chaudhary",
    specialty: "Cardiology",
    specialties: ["Cardiology", "General Medicine"],
    experience: "20 years",
    experience_years: 20,
    hospital: "Delhi NCR",
    rating: 4.8,
    slug: "dr-sanjeev-chaudhary",
    photo_url: "https://satyughealthcare.com/uploads/doctors/492147103510.jpg",
    qualifications: "MBBS, MD - General Medicine, DNB - Cardiology",
    about:
      "Senior Cardiologist with 20 years of experience specializing in interventional cardiology, coronary angiography, pacemaker implantation, and heart failure management.",
  },
  {
    name: "Dr. Rajesh Sharma",
    specialty: "Cardiac Surgery",
    specialties: ["Cardiac Surgery"],
    experience: "28 years",
    experience_years: 28,
    hospital: "AIIMS Delhi",
    rating: 4.9,
    slug: "dr-rajesh-sharma",
    photo_url: "https://www.vaidam.com/sites/default/files/dr._rajesh_sharma_1.png",
    qualifications: "MBBS, MS, MCh Cardiothoracic Surgery",
    about:
      "Senior cardiac surgeon at AIIMS with expertise in complex coronary bypass, valve repair, and paediatric cardiac surgery. Has performed over 10,000 cardiac procedures.",
  },
  {
    name: "Dr. Naresh Trehan",
    specialty: "Cardiac Surgery",
    specialties: ["Cardiac Surgery"],
    experience: "45 years",
    experience_years: 45,
    hospital: "Medanta - The Medicity",
    rating: 4.9,
    slug: "dr-naresh-trehan",
    photo_url: "https://medanta.s3.ap-south-1.amazonaws.com/all-doctor-with-slug/dr-naresh-trehan.png",
    qualifications: "MBBS, MD, FACS",
    about:
      "World-renowned cardiovascular surgeon and Chairman of Medanta. Recipient of Padma Shri and Dr. B. C. Roy Award. Pioneer in minimally invasive cardiac surgery in India.",
  },
  {
    name: "Dr. Priya Singh",
    specialty: "Neurology",
    specialties: ["Neurology"],
    experience: "18 years",
    experience_years: 18,
    hospital: "AIIMS Delhi",
    rating: 4.8,
    slug: "dr-priya-singh",
    photo_url: "https://satyughealthcare.com/uploads/doctors/325417863181.jpg",
    qualifications: "MBBS, MD Medicine, DM Neurology",
    about:
      "Consultant neurologist at AIIMS specializing in stroke care, movement disorders, epilepsy management, and neuro-immunology. Published over 40 research papers.",
  },
  {
    name: "Dr. Ashok Seth",
    specialty: "Cardiology",
    specialties: ["Cardiology"],
    experience: "40 years",
    experience_years: 40,
    hospital: "Fortis Escorts Heart Institute",
    rating: 4.9,
    slug: "dr-ashok-seth",
    photo_url: "https://www.vaidam.com/sites/default/files/dr._ashok_seth.jpg",
    qualifications: "MBBS, MD, DM Cardiology, FACC",
    about:
      "Chairman of Cardiology at Fortis Escorts. Padma Shri awardee and pioneer of coronary angioplasty in India. Has performed over 35,000 coronary interventions.",
  },
  {
    name: "Dr. Arvind Kumar",
    specialty: "Oncology",
    specialties: ["Oncology"],
    experience: "32 years",
    experience_years: 32,
    hospital: "Medanta - The Medicity",
    rating: 4.9,
    slug: "dr-arvind-kumar",
    photo_url: "https://medanta.s3.ap-south-1.amazonaws.com/doctors/October2025/ZiCkhwVIXStutGWAg8de5lCRpq94ui-metaZHItYXJ2aW5kLWt1bWFyLnBuZw==-.png",
    qualifications: "MBBS, MS, MCh Surgical Oncology",
    about:
      "Leading chest and thoracic oncology surgeon at Medanta. Pioneer of minimally invasive thoracic surgery in India. Expert in lung cancer and mediastinal tumor surgery.",
  },
  {
    name: "Dr. Atul Prasad",
    specialty: "Neurology",
    specialties: ["Neurology"],
    experience: "25 years",
    experience_years: 25,
    hospital: "Medanta - The Medicity",
    rating: 4.8,
    slug: "dr-atul-prasad",
    photo_url: "https://www.vaidam.com/sites/default/files/dr.-atul-prasad.jpg",
    qualifications: "MBBS, MD Medicine, DM Neurology",
    about:
      "Principal Director of Neurology at Medanta. Specialist in stroke management, epilepsy surgery evaluation, and neurodegenerative disorders.",
  },
  {
    name: "Dr. Ishwar Bohra",
    specialty: "Orthopedics",
    specialties: ["Orthopedics"],
    experience: "22 years",
    experience_years: 22,
    hospital: "Medanta - The Medicity",
    rating: 4.8,
    slug: "dr-ishwar-bohra",
    photo_url: "https://www.vaidam.com/sites/default/files/dr.ishwar_borah-min.jpg",
    qualifications: "MBBS, MS Orthopedics, FRCS",
    about:
      "Senior orthopedic surgeon at Medanta specializing in hip and knee replacement surgeries. Has performed over 8,000 joint replacement procedures.",
  },
  {
    name: "Dr. Subhash Gupta",
    specialty: "Transplant Surgery",
    specialties: ["Transplant", "Liver Surgery"],
    experience: "30 years",
    experience_years: 30,
    hospital: "Medanta - The Medicity",
    rating: 4.9,
    slug: "dr-subhash-gupta",
    photo_url: "https://www.vaidam.com/sites/default/files/dr-subhash-gupta-liver-transplant-surgeon.jpg",
    qualifications: "MBBS, MS, FRCS",
    about:
      "Chairman of Liver Transplant & Biliary Sciences at Medanta. Has performed over 1,500 living donor liver transplants with success rates matching global standards.",
  },
  {
    name: "Dr. Anupam Saha",
    specialty: "Neurosurgery",
    specialties: ["Neurosurgery"],
    experience: "26 years",
    experience_years: 26,
    hospital: "Apollo Hospitals Delhi",
    rating: 4.8,
    slug: "dr-anupam-saha",
    photo_url: "https://satyughealthcare.com/uploads/doctors/161501531397.jpg",
    qualifications: "MBBS, MS, MCh Neurosurgery",
    about:
      "Senior neurosurgeon at Apollo Indraprastha specializing in brain tumor surgery, spine stabilization, and cerebrovascular interventions.",
  },
  {
    name: "Dr. Sandeep Vaishya",
    specialty: "Neurosurgery",
    specialties: ["Neurosurgery"],
    experience: "28 years",
    experience_years: 28,
    hospital: "Max Super Speciality Hospital Saket",
    rating: 4.8,
    slug: "dr-sandeep-vaishya",
    photo_url: "https://satyughealthcare.com/uploads/doctors/525265157993.png",
    qualifications: "MBBS, MS, MCh Neurosurgery",
    about:
      "Executive Director of Neurosurgery at Max Saket. Specialist in brain tumor surgery, deep brain stimulation, and complex spine surgery.",
  },
  {
    name: "Dr. Rashmi Taluja",
    specialty: "Fertility & IVF",
    specialties: ["Fertility", "IVF"],
    experience: "22 years",
    experience_years: 22,
    hospital: "Artemis Hospital Gurugram",
    rating: 4.8,
    slug: "dr-rashmi-taluja",
    photo_url: "https://satyughealthcare.com/uploads/doctors/617264631571.png",
    qualifications: "MBBS, MS, FRCOG",
    about:
      "Senior IVF and fertility specialist at Artemis Hospital. Specialist in recurrent pregnancy loss, PCOS management, and advanced reproductive techniques including ICSI and egg donation.",
  },
  {
    name: "Dr. H.S. Chhabra",
    specialty: "Spine Surgery",
    specialties: ["Spine Surgery"],
    experience: "38 years",
    experience_years: 38,
    hospital: "Indian Spinal Injuries Centre",
    rating: 4.9,
    slug: "dr-hs-chhabra",
    photo_url: "https://satyughealthcare.com/uploads/doctors/507415075859.jpg",
    qualifications: "MBBS, MS Orthopedics, FICS",
    about:
      "Chief of Spine Services at Indian Spinal Injuries Centre. Pioneer of spine deformity correction and minimally invasive spine surgery in India. Awarded Padma Shri.",
  },
  {
    name: "Dr. Pradeep Sethi",
    specialty: "Paediatric Cardiac Surgery",
    specialties: ["Paediatric Cardiac Surgery"],
    experience: "28 years",
    experience_years: 28,
    hospital: "BLK-Max Super Speciality Hospital",
    rating: 4.9,
    slug: "dr-pradeep-sethi",
    photo_url: "https://satyughealthcare.com/uploads/doctors/492147103510.jpg",
    qualifications: "MBBS, MS, MCh Cardiothoracic Surgery",
    about:
      "Vice Chairman of Paediatric Cardiac Surgery at BLK-Max. Has performed over 6,000 paediatric cardiac surgeries including complex neonatal heart defect repairs.",
  },
  {
    name: "Dr. Deepak K. Tempe",
    specialty: "Cardiology",
    specialties: ["Cardiology"],
    experience: "35 years",
    experience_years: 35,
    hospital: "Sir Ganga Ram Hospital",
    rating: 4.7,
    slug: "dr-deepak-tempe",
    photo_url: "https://satyughealthcare.com/uploads/doctors/811031731733.jpg",
    qualifications: "MBBS, MD, DM Cardiology",
    about:
      "Senior cardiologist at Sir Ganga Ram Hospital with vast experience in interventional cardiology, coronary angioplasty, and pacemaker implantation.",
  },
  {
    name: "Dr. Raju Garg",
    specialty: "Orthopedics",
    specialties: ["Orthopedics"],
    experience: "22 years",
    experience_years: 22,
    hospital: "Apollo Hospitals Delhi",
    rating: 4.8,
    slug: "dr-raju-garg",
    photo_url: "https://satyughealthcare.com/uploads/doctors/492147103510.jpg",
    qualifications: "MBBS, MS Orthopedics, DNB",
    about:
      "Senior orthopedic surgeon at Apollo Indraprastha specializing in hip and knee replacement, arthroscopy, and sports injury management.",
  },
  {
    name: "Dr. Archana Verma",
    specialty: "Ophthalmology",
    specialties: ["Ophthalmology"],
    experience: "22 years",
    experience_years: 22,
    hospital: "Moolchand Hospital",
    rating: 4.7,
    slug: "dr-archana-verma",
    photo_url: "https://www.vaidam.com/sites/default/files/dr._archana-min_1.jpg",
    qualifications: "MBBS, MS, FRCS Ophthalmology",
    about:
      "Senior ophthalmologist at Moolchand Hospital specializing in cataract surgery, retinal disorders, and LASIK procedures.",
  },
  {
    name: "Dr. Vivek Bansal",
    specialty: "Gastroenterology",
    specialties: ["Gastroenterology"],
    experience: "18 years",
    experience_years: 18,
    hospital: "Paras Hospital Gurugram",
    rating: 4.7,
    slug: "dr-vivek-bansal",
    photo_url: "https://www.vaidam.com/sites/default/files/dr._vivek-min_1.jpg",
    qualifications: "MBBS, MD, DM Gastroenterology",
    about:
      "Gastroenterologist at Paras Hospital specializing in therapeutic endoscopy, liver disease management, and bariatric surgery support.",
  },
  {
    name: "Dr. Vikas Dua",
    specialty: "Hematology & BMT",
    specialties: ["Oncology", "Hematology"],
    experience: "20 years",
    experience_years: 20,
    hospital: "Max Super Speciality Hospital Saket",
    rating: 4.8,
    slug: "dr-vikas-dua",
    photo_url: "https://satyughealthcare.com/uploads/doctors/029253041876.png",
    qualifications: "MBBS, MD, DM Hematology",
    about:
      "Director of Paediatric Hematology & Bone Marrow Transplant at Max Saket. Has performed over 500 bone marrow transplants including haploidentical transplants.",
  },
  {
    name: "Dr. Yash Gulati",
    specialty: "Orthopedics",
    specialties: ["Orthopedics"],
    experience: "30 years",
    experience_years: 30,
    hospital: "BLK-Max Super Speciality Hospital",
    rating: 4.8,
    slug: "dr-yash-gulati",
    photo_url: "https://www.vaidam.com/sites/default/files/dr.-yash-gulati-orthopedic-surgeon-compressor-min.jpg",
    qualifications: "MBBS, MS Orthopedics, MCh Orthopedics",
    about:
      "Senior orthopedic surgeon at BLK-Max with expertise in joint replacement, arthroscopy, and sports medicine. Trained in leading orthopedic centres in the UK and Australia.",
  },
  {
    name: "Dr. Anil Arora",
    specialty: "Gastroenterology",
    specialties: ["Gastroenterology"],
    experience: "32 years",
    experience_years: 32,
    hospital: "Sir Ganga Ram Hospital",
    rating: 4.8,
    slug: "dr-anil-arora",
    photo_url: "https://satyughealthcare.com/uploads/doctors/811031731733.jpg",
    qualifications: "MBBS, MD, DM Gastroenterology",
    about:
      "Chairman of Gastroenterology at Sir Ganga Ram Hospital. Expert in therapeutic endoscopy, ERCP, and inflammatory bowel disease management.",
  },
  {
    name: "Dr. Vivek Vij",
    specialty: "Liver Transplant",
    specialties: ["Transplant", "Liver Surgery"],
    experience: "24 years",
    experience_years: 24,
    hospital: "Fortis Memorial Research Institute",
    rating: 4.9,
    slug: "dr-vivek-vij",
    photo_url: "https://www.vaidam.com/sites/default/files/dr_vivek_vij.jpg",
    qualifications: "MBBS, MS, FRCS",
    about:
      "Director of Liver Transplant at Fortis FMRI. Has performed over 1,000 liver transplants. Pioneer in ABO-incompatible liver transplantation in India.",
  },
  {
    name: "Dr. Manoj Miglani",
    specialty: "Orthopedics",
    specialties: ["Orthopedics"],
    experience: "25 years",
    experience_years: 25,
    hospital: "Artemis Hospital Gurugram",
    rating: 4.7,
    slug: "dr-manoj-miglani",
    photo_url: "https://www.vaidam.com/sites/default/files/dr._manoj_miglani_-_orthopedics_and_joint_replacement_surgeon.jpg",
    qualifications: "MBBS, MS Orthopedics, FRCS",
    about:
      "Senior orthopedic surgeon at Artemis Hospital specializing in joint replacement, arthroscopic surgery, and complex trauma reconstruction.",
  },
  {
    name: "Dr. D.S. Rana",
    specialty: "Nephrology",
    specialties: ["Nephrology"],
    experience: "34 years",
    experience_years: 34,
    hospital: "Sir Ganga Ram Hospital",
    rating: 4.8,
    slug: "dr-ds-rana",
    photo_url: "https://satyughealthcare.com/uploads/doctors/492147103510.jpg",
    qualifications: "MBBS, MD, DM Nephrology",
    about:
      "Chairman of Nephrology at Sir Ganga Ram Hospital. Expert in kidney transplant, dialysis management, and chronic kidney disease care.",
  },
  {
    name: "Dr. Z S Meharwal",
    specialty: "Cardiac Surgery",
    specialties: ["Cardiac Surgery"],
    experience: "32 years",
    experience_years: 32,
    hospital: "Fortis Escorts Heart Institute",
    rating: 4.8,
    slug: "dr-zs-meharwal",
    photo_url: "https://www.vaidam.com/sites/default/files/dr-z-s-meharwal_cardio-thorasic-vascular-surgery982956-min.jpg",
    qualifications: "MBBS, MS, MCh Cardiothoracic Surgery",
    about:
      "Senior cardiac surgeon at Fortis Escorts specializing in beating heart bypass surgery, valve repair, and aortic surgery.",
  },
  {
    name: "Dr. Atul Aggarwal",
    specialty: "Neurology",
    specialties: ["Neurology"],
    experience: "24 years",
    experience_years: 24,
    hospital: "Max Super Speciality Hospital Saket",
    rating: 4.8,
    slug: "dr-atul-aggarwal",
    photo_url: "https://satyughealthcare.com/uploads/doctors/525265157993.png",
    qualifications: "MBBS, MD, DM Neurology",
    about:
      "Senior neurologist at Max Saket specializing in stroke management, epilepsy, Parkinson's disease, and dementia care.",
  },
  {
    name: "Dr. Sameer Kaushal",
    specialty: "Cardiology",
    specialties: ["Cardiology"],
    experience: "24 years",
    experience_years: 24,
    hospital: "Manipal Hospital Dwarka",
    rating: 4.7,
    slug: "dr-sameer-kaushal",
    photo_url: "https://satyughealthcare.com/uploads/doctors/029253041876.png",
    qualifications: "MBBS, MD, DM Cardiology",
    about:
      "Senior cardiologist at Manipal Hospital Dwarka specializing in coronary interventions, echocardiography, and preventive cardiology.",
  },
  {
    name: "Dr. Rakesh Gupta",
    specialty: "Cardiology",
    specialties: ["Cardiology"],
    experience: "27 years",
    experience_years: 27,
    hospital: "Artemis Hospital Gurugram",
    rating: 4.7,
    slug: "dr-rakesh-gupta",
    photo_url: "https://satyughealthcare.com/uploads/doctors/492147103510.jpg",
    qualifications: "MBBS, MD, DM Cardiology",
    about:
      "Senior interventional cardiologist at Artemis Hospital specializing in complex coronary interventions, peripheral angioplasty, and structural heart disease treatment.",
  },
  {
    name: "Dr. Simmardeep Gill",
    specialty: "Neurology",
    specialties: ["Neurology"],
    experience: "20 years",
    experience_years: 20,
    hospital: "Fortis Memorial Research Institute",
    rating: 4.7,
    slug: "dr-simmardeep-gill",
    photo_url: "https://satyughealthcare.com/uploads/doctors/161501531397.jpg",
    qualifications: "MBBS, MD, DM Neurology",
    about:
      "Neurologist at Fortis FMRI specializing in stroke interventions, neurocritical care, and multiple sclerosis management.",
  },
  {
    name: "Dr. Sushant Srivastava",
    specialty: "Urology",
    specialties: ["Urology"],
    experience: "18 years",
    experience_years: 18,
    hospital: "Apollo Hospitals Delhi",
    rating: 4.7,
    slug: "dr-sushant-srivastava",
    photo_url: "https://www.vaidam.com/sites/default/files/dr-sushant-srivastava.jpg",
    qualifications: "MBBS, MS, MCh Urology",
    about:
      "Urologist at Apollo Indraprastha specializing in robotic prostate surgery, kidney stone treatment, and uro-oncology.",
  },
  {
    name: "Dr. Aditi Sharma",
    specialty: "Fertility & IVF",
    specialties: ["Fertility", "IVF"],
    experience: "16 years",
    experience_years: 16,
    hospital: "BLK-Max Super Speciality Hospital",
    rating: 4.7,
    slug: "dr-aditi-sharma",
    photo_url: "https://satyughealthcare.com/uploads/doctors/617264631571.png",
    qualifications: "MBBS, MD, DNB Obstetrics & Gynecology",
    about:
      "Fertility specialist at BLK-Max with expertise in IVF, ICSI, fertility preservation, and reproductive endocrinology.",
  },
  {
    name: "Dr. Anurag Saxena",
    specialty: "Oncology",
    specialties: ["Oncology"],
    experience: "22 years",
    experience_years: 22,
    hospital: "Fortis Memorial Research Institute",
    rating: 4.8,
    slug: "dr-anurag-saxena",
    photo_url: "https://www.vaidam.com/sites/default/files/dr._anurag_saxena_neurosurgeon_2.png",
    qualifications: "MBBS, MD, DM Medical Oncology",
    about:
      "Senior medical oncologist at Fortis FMRI specializing in breast cancer, lung cancer, and hematological malignancies. Expert in targeted therapy and immunotherapy.",
  },
  {
    name: "Dr. Vivek Loomba",
    specialty: "Orthopedics",
    specialties: ["Orthopedics"],
    experience: "20 years",
    experience_years: 20,
    hospital: "Manipal Hospital Dwarka",
    rating: 4.6,
    slug: "dr-vivek-loomba",
    photo_url: "https://satyughealthcare.com/uploads/doctors/161501531397.jpg",
    qualifications: "MBBS, MS Orthopedics",
    about:
      "Orthopedic surgeon at Manipal Hospital Dwarka specializing in joint replacement, arthroscopy, and trauma surgery.",
  },
  {
    name: "Dr. Rajendra Kumar",
    specialty: "Cardiology",
    specialties: ["Cardiology"],
    experience: "26 years",
    experience_years: 26,
    hospital: "Narayana Superspeciality Hospital Gurugram",
    rating: 4.7,
    slug: "dr-rajendra-kumar",
    photo_url: "https://satyughealthcare.com/uploads/doctors/811031731733.jpg",
    qualifications: "MBBS, MD, DM Cardiology",
    about:
      "Senior cardiologist at Narayana Superspeciality Hospital Gurugram specializing in high-volume coronary interventions and heart failure management.",
  },
  {
    name: "Dr. Alok Gupta",
    specialty: "Orthopedics",
    specialties: ["Orthopedics"],
    experience: "20 years",
    experience_years: 20,
    hospital: "Columbia Asia Hospital Gurugram",
    rating: 4.6,
    slug: "dr-alok-gupta",
    photo_url: "https://www.vaidam.com/sites/default/files/dr._alok_gupta_-_minimal_access_bariatric_laparoscopic_surgery.jpg",
    qualifications: "MBBS, MS Orthopedics",
    about:
      "Orthopedic surgeon at Columbia Asia Hospital Gurugram specializing in joint replacement, arthroscopy, and sports injuries.",
  },
  {
    name: "Dr. Amit Kumar",
    specialty: "Orthopedics",
    specialties: ["Orthopedics"],
    experience: "20 years",
    experience_years: 20,
    hospital: "AIIMS Delhi",
    rating: 4.7,
    slug: "dr-amit-kumar",
    photo_url: "https://www.vaidam.com/sites/default/files/dr-amit-kumar-cardiologist_1.jpg",
    qualifications: "MBBS, MS Orthopedics",
    about:
      "Orthopedic surgeon at AIIMS specializing in joint replacement, spine surgery, and trauma management.",
  },
];

export const fallbackHospitals = [
  {
    name: "All India Institute of Medical Sciences (AIIMS)",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "2,478+",
    beds_count: 2478,
    accreditation: "NABH, Govt of India",
    accreditations: ["NABH", "Govt of India"],
    slug: "aiims-delhi",
    photo_url: "https://upload.wikimedia.org/wikipedia/commons/c/cd/AIIMS_-New_Delhi%27s_Ward_Block.jpg",
    about:
      "AIIMS is India's premier medical institution and hospital, renowned for its high-quality patient care, medical education, and research. With over 2,400 beds and 600+ specialists, it offers comprehensive treatment across all major specialties at highly affordable rates.",
  },
  {
    name: "Medanta - The Medicity",
    location: "Gurugram, Haryana",
    city: "Gurugram",
    state: "Haryana",
    beds: "1,250+",
    beds_count: 1250,
    accreditation: "JCI, NABH",
    accreditations: ["JCI", "NABH"],
    slug: "medanta-the-medicity",
    photo_url: "https://medanta.s3.ap-south-1.amazonaws.com/hospitals/January2024/rRYbW6Ah4XKY0c6se2UgwXkV4p6NXb-metaR1VSVUdSQU0ucG5n-.png",
    about:
      "Medanta is one of India's largest multi-specialty hospitals with a dedicated international patient wing. It features 45+ operating theatres, advanced robotic surgery systems, and world-renowned cardiac, oncology, transplant, and orthopaedic programs.",
  },
  {
    name: "Apollo Hospitals Indraprastha",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "700+",
    beds_count: 700,
    accreditation: "JCI, NABH",
    accreditations: ["JCI", "NABH"],
    slug: "apollo-hospitals-delhi",
    photo_url: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Indraprastha_Apollo_Hospital.jpg",
    about:
      "Apollo Hospitals Indraprastha is a flagship tertiary care hospital in South East Asia with internationally accredited programs in cardiac sciences, oncology, neurosciences, orthopedics, and organ transplantation.",
  },
  {
    name: "Fortis Escorts Heart Institute",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "485+",
    beds_count: 485,
    accreditation: "JCI, NABH",
    accreditations: ["JCI", "NABH"],
    slug: "fortis-escorts-heart-institute",
    photo_url: "https://medanta.s3.ap-south-1.amazonaws.com/hospitals/February2025/KRKHMv9Fxr54fLXKN0OjZzxiiwFTBq-metaT2JSZkdhUTI1bnJwWldCdkJKMWxzdHBCVG91cEdNLW1ldGFSM1Z5ZFdkeVlXMHVhbkJuLS5qcGc=-.jpg",
    about:
      "Fortis Escorts Heart Institute is India's most recognised cardiac care hospital, performing over 15,000 cardiac surgeries annually with world-class success rates.",
  },
  {
    name: "Max Super Speciality Hospital Saket",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "680+",
    beds_count: 680,
    accreditation: "JCI, NABH",
    accreditations: ["JCI", "NABH"],
    slug: "max-super-speciality-hospital-saket",
    photo_url: "https://medanta.s3.ap-south-1.amazonaws.com/hospitals/September2023/7SQ9q1Q1OCZRgZRErb64rLCNhnUGSi-metabHVja25vdy5qcGc=-.jpg",
    about:
      "Max Super Speciality Hospital Saket is a multi-specialty tertiary care hospital known for its advanced neurosciences, bone marrow transplant program, cardiac care, and oncology services.",
  },
  {
    name: "Sir Ganga Ram Hospital",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "650+",
    beds_count: 650,
    accreditation: "NABH, ISO 9001",
    accreditations: ["NABH", "ISO 9001"],
    slug: "sir-ganga-ram-hospital",
    photo_url: "https://medanta.s3.ap-south-1.amazonaws.com/hospitals/February2025/YelIyqoA5uGHAsU26kWk9EH54Aumyv-metaUGF0bmEgSG9zcGl0YWwgSW1hZ2UgKDIpLmpwZw==-.jpg",
    about:
      "Sir Ganga Ram Hospital is a premier multi-specialty hospital in New Delhi with a 70-year legacy of medical excellence across cardiology, gastroenterology, nephrology, and urology.",
  },
  {
    name: "BLK-Max Super Speciality Hospital",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "650+",
    beds_count: 650,
    accreditation: "JCI, NABH",
    accreditations: ["JCI", "NABH"],
    slug: "blk-max-super-speciality-hospital",
    photo_url: "https://upload.wikimedia.org/wikipedia/commons/3/32/BLK_Super_Specialty_Hospital.jpg",
    about:
      "BLK-Max Super Speciality Hospital is a leading healthcare facility in Central Delhi with 650 beds and 17 super-speciality departments, renowned for paediatric cardiac surgery, orthopedics, and fertility treatment.",
  },
  {
    name: "Artemis Hospital Gurugram",
    location: "Gurugram, Haryana",
    city: "Gurugram",
    state: "Haryana",
    beds: "500+",
    beds_count: 500,
    accreditation: "JCI, NABH",
    accreditations: ["JCI", "NABH"],
    slug: "artemis-hospital-gurugram",
    photo_url: "https://medanta.s3.ap-south-1.amazonaws.com/hospitals/April2025/sdE5SGg6gM0Y4fqeIaLSlnZO7bE8Rq-metaSW5kb3JlIGhvc3BpdGFsIDEuanBn-.jpg",
    about:
      "Artemis Hospital is a state-of-the-art multi-specialty hospital in Gurugram with JCI accreditation, offering advanced care in cardiology, orthopedics, IVF, and oncology with a focus on medical tourism.",
  },
  {
    name: "Fortis Memorial Research Institute",
    location: "Gurugram, Haryana",
    city: "Gurugram",
    state: "Haryana",
    beds: "1,000+",
    beds_count: 1000,
    accreditation: "JCI, NABH",
    accreditations: ["JCI", "NABH"],
    slug: "fortis-memorial-research-institute",
    photo_url: "https://medanta.s3.ap-south-1.amazonaws.com/hospitals/January2024/vv3jGl55XyYhdw6Css4eETU7I3cSty-metaTHVja25vdy5wbmc=-.png",
    about:
      "Fortis Memorial Research Institute (FMRI) is a flagship quaternary care hospital with dedicated centres for oncology, neurosciences, orthopedics, cardiac care, and liver transplant.",
  },
  {
    name: "Manipal Hospital Dwarka",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "380+",
    beds_count: 380,
    accreditation: "NABH, ISO 9001",
    accreditations: ["NABH", "ISO 9001"],
    slug: "manipal-hospital-dwarka",
    photo_url: "https://medanta.s3.ap-south-1.amazonaws.com/hospitals/January2024/CrIXV6svcbfI8IwaGIINKGH4rNzSan-metaUGF0bmEucG5n-.png",
    about:
      "Manipal Hospital Dwarka is a multi-specialty tertiary care hospital serving West Delhi with comprehensive healthcare services including cardiology, orthopedics, neurology, and gastroenterology.",
  },
  {
    name: "Indian Spinal Injuries Centre",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "250+",
    beds_count: 250,
    accreditation: "NABH, ISO 9001",
    accreditations: ["NABH", "ISO 9001"],
    slug: "indian-spinal-injuries-centre",
    photo_url: "https://medanta.s3.ap-south-1.amazonaws.com/hospitals/January2024/UG8G445YMpH2rBUJCF8zJlK52TbUFG-metaSW5kb3JlLnBuZw==-.png",
    about:
      "The Indian Spinal Injuries Centre is Asia's premier institute for spine care and rehabilitation, offering comprehensive treatment for spinal trauma, degenerative spine conditions, and sports injuries.",
  },
  {
    name: "Venkateshwar Hospital",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "350+",
    beds_count: 350,
    accreditation: "NABH",
    accreditations: ["NABH"],
    slug: "venkateshwar-hospital",
    photo_url: "https://medanta.s3.ap-south-1.amazonaws.com/hospitals/September2025/tueLPci3oHXKmxX7Uz2mnvpMD4M6PE-metaNDgwX3hfMzIwLndlYnA=-.webp",
    about:
      "Venkateshwar Hospital is a multi-super-speciality hospital in Dwarka offering advanced medical care in gastroenterology, cardiology, orthopedics, nephrology, and general surgery.",
  },
  {
    name: "Saroj Super Speciality Hospital",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "300+",
    beds_count: 300,
    accreditation: "NABH",
    accreditations: ["NABH"],
    slug: "saroj-super-speciality-hospital",
    photo_url: "https://medanta.s3.ap-south-1.amazonaws.com/hospitals/April2025/W745nIg3xEkkTksRkH6pFvEAgCyo7D-metaRjdnUkJWYWNqVU1qM1lTaHllazBwZTVHV0lxUDJDLW1ldGFVbUZ1WTJocElEVXhOQ0FnZUNBME1EQXVjRzVuLS5wbmc=-.png",
    about:
      "Saroj Super Speciality Hospital is a well-established medical facility in Central Delhi known for its urology, nephrology, and general surgery departments at affordable prices.",
  },
  {
    name: "Paras Hospital Gurugram",
    location: "Gurugram, Haryana",
    city: "Gurugram",
    state: "Haryana",
    beds: "350+",
    beds_count: 350,
    accreditation: "NABH, ISO 9001",
    accreditations: ["NABH", "ISO 9001"],
    slug: "paras-hospital-gurugram",
    photo_url: "https://medanta.s3.ap-south-1.amazonaws.com/hospitals/February2025/KRKHMv9Fxr54fLXKN0OjZzxiiwFTBq-metaT2JSZkdhUTI1bnJwWldCdkJKMWxzdHBCVG91cEdNLW1ldGFSM1Z5ZFdkeVlXMHVhbkJuLS5qcGc=-.jpg",
    about:
      "Paras Hospital is a multi-specialty tertiary care hospital in Gurugram with expertise in gastroenterology, bariatric surgery, orthopedics, and fertility treatment.",
  },
  {
    name: "Narayana Superspeciality Hospital Gurugram",
    location: "Gurugram, Haryana",
    city: "Gurugram",
    state: "Haryana",
    beds: "450+",
    beds_count: 450,
    accreditation: "NABH, ISO 9001",
    accreditations: ["NABH", "ISO 9001"],
    slug: "narayana-superspeciality-hospital-gurugram",
    photo_url: "https://medanta.s3.ap-south-1.amazonaws.com/hospitals/April2025/sdE5SGg6gM0Y4fqeIaLSlnZO7bE8Rq-metaSW5kb3JlIGhvc3BpdGFsIDEuanBn-.jpg",
    about:
      "Narayana Superspeciality Hospital is part of the renowned Narayana Health chain, offering affordable cardiac care, oncology, orthopedics, and neurosurgery with outcomes matching global benchmarks.",
  },
  {
    name: "Moolchand Hospital",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "325+",
    beds_count: 325,
    accreditation: "NABH, ISO 9001",
    accreditations: ["NABH", "ISO 9001"],
    slug: "moolchand-hospital",
    photo_url: "https://medanta.s3.ap-south-1.amazonaws.com/hospitals/September2023/7SQ9q1Q1OCZRgZRErb64rLCNhnUGSi-metabHVja25vdy5qcGc=-.jpg",
    about:
      "Moolchand Hospital is a 325-bed multi-specialty hospital in South Delhi with a 70-year legacy, offering comprehensive care in ophthalmology, orthopedics, cardiology, and women's health.",
  },
  {
    name: "Columbia Asia Hospital Gurugram",
    location: "Gurugram, Haryana",
    city: "Gurugram",
    state: "Haryana",
    beds: "200+",
    beds_count: 200,
    accreditation: "JCI, NABH",
    accreditations: ["JCI", "NABH"],
    slug: "columbia-asia-hospital-gurugram",
    photo_url: "https://medanta.s3.ap-south-1.amazonaws.com/hospitals/January2024/vv3jGl55XyYhdw6Css4eETU7I3cSty-metaTHVja25vdy5wbmc=-.png",
    about:
      "Columbia Asia Hospital is a JCI-accredited tertiary care facility in Gurugram offering comprehensive services in orthopedics, cardiology, and general surgery.",
  },
];

export const fallbackTreatments = [
  {
    name: "Liver Transplant Surgery",
    costMin: 28000,
    costMax: 45000,
    usCost: 180000,
    slug: "liver-transplant",
    category: "Transplant",
    description:
      "Living donor and cadaveric liver transplant at NABH accredited hospitals in India. Includes pre-transplant evaluation, surgery, ICU care, and post-transplant follow-up.",
    image_url: "https://satyughealthcare.com/uploads/treatment_package/071607183870.png",
  },
  {
    name: "Kidney Transplant",
    costMin: 13000,
    costMax: 18000,
    usCost: 75000,
    slug: "kidney-transplant",
    category: "Transplant",
    description:
      "Kidney transplant surgery with living or cadaveric donor at top hospitals. Package includes donor evaluation, surgery, immunosuppression planning, and recovery.",
    image_url: "https://satyughealthcare.com/uploads/treatment_package/884152601829.jpg",
  },
  {
    name: "Bone Marrow Transplant",
    costMin: 18000,
    costMax: 35000,
    usCost: 250000,
    slug: "bone-marrow-transplant",
    category: "Oncology",
    description:
      "Allogeneic and autologous BMT for leukemia, lymphoma, and blood disorders. Includes HLA matching, conditioning, transplant, and engraftment monitoring.",
    image_url: "https://satyughealthcare.com/uploads/treatment_package/510593914830.jpg",
  },
  {
    name: "Knee Replacement",
    costMin: 5000,
    costMax: 7000,
    usCost: 45000,
    slug: "knee-replacement",
    category: "Orthopedics",
    description:
      "Total and partial knee replacement with imported implants at JCI hospitals. Includes pre-op assessment, surgery, physiotherapy, and discharge planning.",
    image_url: "https://satyughealthcare.com/uploads/treatment_package/318445058417.jpg",
  },
  {
    name: "Hip Replacement",
    costMin: 6000,
    costMax: 8000,
    usCost: 50000,
    slug: "hip-replacement",
    category: "Orthopedics",
    description:
      "Total hip replacement and hip resurfacing with latest prosthetics. Includes hospital stay, rehabilitation, and follow-up care.",
    image_url: "https://satyughealthcare.com/uploads/treatment_package/001428941542.jpg",
  },
  {
    name: "Spine Surgery",
    costMin: 5000,
    costMax: 10000,
    usCost: 65000,
    slug: "spine-surgery",
    category: "Orthopedics",
    description:
      "Minimally invasive spine surgery, disc replacement, spinal fusion, and deformity correction by expert spine surgeons.",
    image_url: "https://satyughealthcare.com/uploads/treatment_package/146787701787.png",
  },
  {
    name: "Heart Bypass Surgery (CABG)",
    costMin: 7000,
    costMax: 10000,
    usCost: 100000,
    slug: "heart-bypass-surgery",
    category: "Cardiology",
    description:
      "Coronary artery bypass grafting including on-pump and off-pump techniques. Includes pre-op evaluation, ICU stay, and cardiac rehabilitation.",
    image_url: "https://satyughealthcare.com/uploads/treatment_package/155192473072.png",
  },
  {
    name: "Angioplasty and Stenting",
    costMin: 3500,
    costMax: 6000,
    usCost: 30000,
    slug: "angioplasty",
    category: "Cardiology",
    description:
      "Coronary angioplasty with drug-eluting stent placement. Includes cardiac catheterization, stent procedure, monitoring, and follow-up.",
    image_url: "https://satyughealthcare.com/uploads/treatment_package/796098408516.jpg",
  },
  {
    name: "IVF Treatment",
    costMin: 3000,
    costMax: 5000,
    usCost: 20000,
    slug: "ivf-treatment",
    category: "Fertility",
    description:
      "Complete IVF cycle including ovarian stimulation, egg retrieval, embryo culture, transfer, and pregnancy testing at top fertility centers.",
    image_url: "https://satyughealthcare.com/uploads/treatment_package/274716752857.png",
  },
  {
    name: "Hair Transplant",
    costMin: 1500,
    costMax: 3000,
    usCost: 15000,
    slug: "hair-transplant",
    category: "Cosmetic",
    description:
      "FUE and FUT hair transplant with natural results. Includes consultation, graft planning, procedure, and post-care instructions.",
    image_url: "https://satyughealthcare.com/uploads/treatment_package/274716752857.png",
  },
  {
    name: "Bariatric Surgery",
    costMin: 5000,
    costMax: 7500,
    usCost: 25000,
    slug: "bariatric-surgery",
    category: "Gastroenterology",
    description:
      "Gastric sleeve, gastric bypass, and mini gastric bypass. Includes nutritionist consultation, surgery, and long-term diet planning.",
    image_url: "https://satyughealthcare.com/uploads/treatment_package/102136737103.png",
  },
  {
    name: "Brain Tumor Surgery",
    costMin: 6500,
    costMax: 10000,
    usCost: 80000,
    slug: "brain-tumor-surgery",
    category: "Neurology",
    description:
      "Craniotomy and minimally invasive brain tumor removal with neuro-navigation guided surgery and ICU care by experienced neurosurgeons.",
    image_url: "https://satyughealthcare.com/uploads/treatment_package/216514607672.png",
  },
  {
    name: "Aortic Valve Replacement",
    costMin: 8000,
    costMax: 12000,
    usCost: 80000,
    slug: "aortic-valve-replacement",
    category: "Cardiology",
    description:
      "Surgical and transcatheter aortic valve replacement (TAVR/SAVR). Includes cardiac evaluation and post-operative monitoring.",
    image_url: "https://satyughealthcare.com/uploads/treatment_package/816018845104.jpg",
  },
  {
    name: "Oncology Surgery",
    costMin: 5000,
    costMax: 15000,
    usCost: 80000,
    slug: "oncology-surgery",
    category: "Oncology",
    description:
      "Surgical oncology for breast, lung, colon, and stomach cancers. Includes tumor board review, surgery, and chemo planning.",
    image_url: "https://satyughealthcare.com/uploads/treatment_package/786610918089.jpg",
  },
  {
    name: "Scoliosis Correction Surgery",
    costMin: 8000,
    costMax: 15000,
    usCost: 100000,
    slug: "scoliosis-surgery",
    category: "Orthopedics",
    description:
      "Spinal deformity correction for adolescent and adult scoliosis with advanced instrumentation and comprehensive rehabilitation.",
    image_url: "https://satyughealthcare.com/uploads/treatment_package/728155135898.jpg",
  },
];

export const fallbackTestimonials = [
  {
    name: "Grace Mwangi",
    country: "Kenya",
    treatment: "Knee Replacement",
    text:
      "I had been suffering from knee pain for years. Asians Healthcare made everything easy - from my visa to hospital stay. The doctors were exceptional.",
    rating: 5,
    videoId: "oB2GzmHqVBM",
  },
  {
    name: "Ahmed Al-Rashid",
    country: "Iraq",
    treatment: "Liver Transplant",
    text:
      "Finding a reliable medical tourism facilitator was my biggest concern. Asians Healthcare exceeded all expectations and coordinated everything perfectly.",
    rating: 5,
    videoId: "3rUulNKF26s",
  },
  {
    name: "Fatima Okafor",
    country: "Nigeria",
    treatment: "IVF Treatment",
    text:
      "After years of trying, Asians Healthcare helped us start our family. The entire team was supportive and professional.",
    rating: 5,
    videoId: "O-Dp9aHZldA",
  },
  {
    name: "James Mwangi",
    country: "Kenya",
    treatment: "Cardiac Bypass",
    text:
      "My heart surgery at Medanta was life-changing. The coordination by Asians Healthcare was flawless from Nairobi to Delhi and back.",
    rating: 5,
    videoId: "",
  },
  {
    name: "Raj Patel",
    country: "United Kingdom",
    treatment: "Hip Replacement",
    text:
      "The cost savings were substantial but the quality of care was world-class. I would recommend Asians Healthcare to anyone considering treatment in India.",
    rating: 5,
    videoId: "",
  },
  {
    name: "Nadia Khan",
    country: "Bangladesh",
    treatment: "Kidney Transplant",
    text:
      "My brother received a life-saving kidney transplant through Asians Healthcare. The coordination, hospital selection, and follow-up were outstanding.",
    rating: 5,
    videoId: "",
  },
];

export const fallbackInsurances = [
  "AAR Insurance Africa",
  "Allianz Care",
  "Britam Health Insurance",
  "Bupa Global",
  "Cigna Global",
  "Jubilee Insurance",
  "SHA Kenya",
  "UAP Old Mutual Insurance",
];

export const fallbackHotels = [
  {
    name: "The Leela Palace New Delhi",
    address: "Chanakyapuri, New Delhi",
    stars: 5,
    price: "$$$$",
    near: "Diplomatic Enclave",
    description: "An ultra-luxury palace hotel in the heart of New Delhi's diplomatic enclave. Known for its opulent interiors, world-class dining, and impeccable service. Features a rooftop pool, luxury spa, and fine dining restaurants.",
    photo_url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80",
  },
  {
    name: "The Taj Mahal Hotel New Delhi",
    address: "1, Mansingh Road, New Delhi",
    stars: 5,
    price: "$$$$",
    near: "India Gate",
    description: "An iconic luxury hotel overlooking Lutyens' Delhi. The Taj Mahal Hotel has hosted world leaders and dignitaries since 1978. Features exquisite restaurants, a luxury spa, and beautifully landscaped gardens.",
    photo_url: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&q=80",
  },
  {
    name: "ITC Maurya New Delhi",
    address: "Sardar Patel Marg, Chanakyapuri, New Delhi",
    stars: 5,
    price: "$$$$",
    near: "Diplomatic Enclave",
    description: "A legendary luxury hotel known for hosting heads of state. Home to Bukhara restaurant, consistently rated among the world's best. Features palatial architecture, award-winning cuisine, and the exclusive Towers wing.",
    photo_url: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600&q=80",
  },
  {
    name: "The Imperial New Delhi",
    address: "Janpath, Connaught Place, New Delhi",
    stars: 5,
    price: "$$$$",
    near: "Connaught Place",
    description: "A heritage art deco hotel from 1931 on Janpath. The Imperial houses one of India's finest private art collections. Known for The Spice Route restaurant, 1911 bar, and its colonial-era grandeur.",
    photo_url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80",
  },
  {
    name: "The Oberoi New Delhi",
    address: "Dr. Zakir Hussain Marg, New Delhi",
    stars: 5,
    price: "$$$$",
    near: "Humayun's Tomb & Delhi Golf Club",
    description: "A modern luxury hotel overlooking the Delhi Golf Club greens. Recently renovated with contemporary design, featuring Threesixtyone\u00b0 restaurant, luxury spa, and stunning city views from every room.",
    photo_url: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=600&q=80",
  },
  {
    name: "Hyatt Regency Delhi",
    address: "Bhikaji Cama Place, Ring Road, New Delhi",
    stars: 5,
    price: "$$$",
    near: "AIIMS & Safdarjung Hospital",
    description: "A prominent 5-star hotel near major medical institutions including AIIMS. Features multiple dining options, a large outdoor pool, fitness center, and well-appointed rooms ideal for medical tourists.",
    photo_url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&q=80",
  },
  {
    name: "Shangri-La Eros New Delhi",
    address: "19, Ashoka Road, Connaught Place, New Delhi",
    stars: 5,
    price: "$$$$",
    near: "Connaught Place",
    description: "A luxury hotel in the heart of New Delhi near Connaught Place. Known for its spacious rooms, signature Chi Spa, rooftop bar with Parliament views, and award-winning Asian dining at Shang Palace.",
    photo_url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80",
  },
  {
    name: "Le Meridien New Delhi",
    address: "Windsor Place, Janpath, New Delhi",
    stars: 5,
    price: "$$$",
    near: "Connaught Place & Janpath",
    description: "A distinctive cylindrical tower hotel on Janpath. Centrally located near Connaught Place, featuring a unique atrium design, rooftop pool, multiple restaurants, and convenient access to metro and major landmarks.",
    photo_url: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=600&q=80",
  },
  {
    name: "ITC Wellingdon New Delhi",
    address: "Connaught Place, New Delhi",
    stars: 5,
    price: "$$$$",
    near: "Connaught Place",
    description: "A boutique luxury hotel by ITC in the heart of Connaught Place. Features personalized butler service, the acclaimed Dum Pukht Jolly Nabobs restaurant, rooftop bar, and intimate luxury in just 100 rooms.",
    photo_url: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&q=80",
  },
  {
    name: "Taj Palace New Delhi",
    address: "2, Sardar Patel Marg, Chanakyapuri, New Delhi",
    stars: 5,
    price: "$$$$",
    near: "Dhaula Kuan",
    description: "A grand luxury hotel set on 6 acres of landscaped gardens. Features 403 rooms, the legendary Orient Express restaurant, Blue Bar, luxury spa, and is a preferred choice for state banquets and international conferences.",
    photo_url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=600&q=80",
  },
  {
    name: "Radisson Blu Plaza Delhi",
    address: "National Highway 8, Mahipalpur, New Delhi",
    stars: 5,
    price: "$$$",
    near: "IGI Airport & Fortis Hospital",
    description: "A premium airport hotel just minutes from IGI Airport and close to Fortis Hospital. Ideal for medical tourists arriving late or departing early. Features modern rooms, a large pool, spa, and multiple dining options.",
    photo_url: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=600&q=80",
  },
  {
    name: "The Claridges New Delhi",
    address: "12, Dr APJ Abdul Kalam Road, New Delhi",
    stars: 5,
    price: "$$$$",
    near: "India Gate & Lodhi Garden",
    description: "A heritage luxury hotel since 1952 on tree-lined Aurangzeb Road. Known for Sevilla restaurant, Dhaba by Claridges, afternoon teas, and its old-world colonial charm amidst modern luxury.",
    photo_url: "https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=600&q=80",
  },
  {
    name: "JW Marriott Hotel New Delhi Aerocity",
    address: "Asset Area 4, Hospitality District, Aerocity, New Delhi",
    stars: 5,
    price: "$$$",
    near: "IGI Airport",
    description: "A contemporary luxury hotel in Aerocity near the airport. Features 523 rooms, K3 all-day dining, Adrift Kaya Japanese restaurant, expansive spa, and excellent connectivity to South Delhi hospitals.",
    photo_url: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=600&q=80",
  },
  {
    name: "Pullman New Delhi Aerocity",
    address: "Asset 2, Hospitality District, Aerocity, New Delhi",
    stars: 5,
    price: "$$$",
    near: "IGI Airport & Medanta Medicity",
    description: "A stylish French hospitality brand hotel in Aerocity. Known for its vibrant Pluck restaurant, rooftop Pling bar, infinity pool, and modern design. Great access to Gurugram hospitals via expressway.",
    photo_url: "https://images.unsplash.com/photo-1606402179428-a57976d71fa4?w=600&q=80",
  },
  {
    name: "The Lodhi New Delhi",
    address: "Lodhi Road, New Delhi",
    stars: 5,
    price: "$$$$",
    near: "Lodhi Garden & Max Hospital",
    description: "An all-suite luxury boutique hotel with private plunge pools. Set amidst 7 acres of gardens near Lodhi Garden. Features Indian Accent restaurant, Elan spa, and is close to Max and Apollo hospitals in South Delhi.",
    photo_url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80",
  },
];

export const fallbackSpecialties = [
  {
    name: "Cardiology",
    slug: "cardiology",
    desc: "Heart care, bypass surgery, valve replacement, angioplasty, and cardiac rehabilitation.",
  },
  {
    name: "Orthopedics",
    slug: "orthopedics",
    desc: "Joint replacement, spine care, sports injury treatment, and fracture management.",
  },
  {
    name: "Neurology",
    slug: "neurology",
    desc: "Stroke care, spine disorders, movement disorders, epilepsy, and neurosurgery coordination.",
  },
  {
    name: "Oncology",
    slug: "oncology",
    desc: "Cancer diagnosis, chemotherapy, radiation therapy, surgical oncology, and second opinions.",
  },
  {
    name: "Gastroenterology",
    slug: "gastroenterology",
    desc: "Digestive health, liver care, bariatric surgery, endoscopy, and transplant evaluation.",
  },
  {
    name: "Nephrology",
    slug: "nephrology",
    desc: "Kidney disease care, dialysis planning, transplant evaluation, and post-treatment support.",
  },
  {
    name: "Urology",
    slug: "urology",
    desc: "Kidney stones, prostate care, robotic urology surgery, and male reproductive health.",
  },
  {
    name: "Fertility",
    slug: "fertility",
    desc: "IVF, ICSI, fertility diagnostics, embryo transfer, and reproductive medicine coordination.",
  },
  {
    name: "Transplant",
    slug: "transplant",
    desc: "Kidney, liver, and bone marrow transplant evaluation with long-stay support planning.",
  },
  {
    name: "Dental",
    slug: "dental",
    desc: "Dental implants, smile design, oral surgery, and staged treatment planning for visitors.",
  },
  {
    name: "Ophthalmology",
    slug: "ophthalmology",
    desc: "Cataract, retina, LASIK, glaucoma, and advanced eye-care procedures.",
  },
  {
    name: "Cosmetic Surgery",
    slug: "cosmetic-surgery",
    desc: "Aesthetic and reconstructive procedures with privacy-focused recovery planning.",
  },
];

export const fallbackBlogs = [
  {
    title: "Why Medical Tourism in India Is Growing: A Complete Guide",
    slug: "medical-tourism-india-guide",
    category: "Treatment Blog",
    author: "Asians Healthcare",
    published_at: "2025-12-15T00:00:00Z",
    thumbnail_url: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Indraprastha_Apollo_Hospital.jpg",
    content: `<h2>Why India Is a Top Destination for Medical Tourism</h2>
<p>India has emerged as one of the world's leading medical tourism destinations, attracting patients from over 80 countries. With JCI and NABH-accredited hospitals, internationally trained doctors, and treatment costs that are 60-80% lower than in Western countries, India offers exceptional value for medical travelers.</p>
<h2>Key Advantages</h2>
<p><strong>World-Class Healthcare:</strong> India's top hospitals like Apollo, Max, and Artemis maintain international standards with advanced technology and highly skilled specialists. Many have dedicated international patient desks to coordinate your entire journey.</p>
<p><strong>Cost Savings:</strong> A heart bypass surgery that costs $100,000+ in the US can be performed in India for $7,000-$10,000. Hip replacement costs $12,000 in the US versus $4,000 in India. These savings include hospital stay, surgeon fees, and follow-up care.</p>
<p><strong>No Waiting Lists:</strong> Unlike many countries where patients wait months for elective procedures, Indian hospitals can schedule surgeries within days of consultation, making it ideal for time-sensitive treatments.</p>
<h2>Steps to Plan Your Medical Trip</h2>
<ol><li>Share your medical reports with our team</li><li>Receive matched doctor and hospital recommendations</li><li>Get a detailed cost estimate and treatment plan</li><li>Receive visa invitation and travel guidance</li><li>Arrive in India with airport pickup and accommodation arranged</li></ol>`,
  },
  {
    title: "Top 10 Hospitals in Delhi NCR for International Patients",
    slug: "top-hospitals-delhi-international-patients",
    category: "Medical Visa Guide",
    author: "Asians Healthcare",
    published_at: "2025-11-20T00:00:00Z",
    thumbnail_url: "https://medanta.s3.ap-south-1.amazonaws.com/hospitals/January2024/rRYbW6Ah4XKY0c6se2UgwXkV4p6NXb-metaR1VSVUdSQU0ucG5n-.png",
    content: `<h2>Best Hospitals in Delhi NCR</h2>
<p>Delhi's National Capital Region hosts some of India's finest healthcare institutions, many with dedicated international patient departments. Here are the top hospitals that cater to medical travelers.</p>
<h2>1. Apollo Hospitals Indraprastha</h2>
<p>A flagship tertiary care hospital with internationally accredited programs in cardiac sciences, oncology, neurosciences, and organ transplantation. Apollo's International Patient Services handles over 10,000 international patients annually.</p>
<h2>2. Max Super Speciality Hospital Saket</h2>
<p>Known for advanced neurosciences, bone marrow transplant, and cardiac care. Max has a dedicated International Lounge with translators, visa assistance, and concierge services.</p>
<h2>3. Artemis Hospital Gurugram</h2>
<p>JCI-accredited with state-of-the-art infrastructure. Artemis excels in cardiology, orthopedics, IVF, and oncology with a strong focus on medical tourism comfort.</p>
<h2>4. BLK-Max Super Speciality Hospital</h2>
<p>650-bed facility in Central Delhi renowned for paediatric cardiac surgery, orthopedics, and fertility treatment. BLK has one of India's largest bone marrow transplant units.</p>
<h2>Important Considerations</h2>
<p>When choosing a hospital, consider JCI/NABH accreditation, the hospital's experience with international patients, available translators, and post-discharge follow-up protocols.</p>`,
  },
  {
    title: "Understanding Medical Visa Procedures for India",
    slug: "medical-visa-india-procedures",
    category: "Medical Visa Guide",
    author: "Asians Healthcare",
    published_at: "2025-10-10T00:00:00Z",
    thumbnail_url: "https://upload.wikimedia.org/wikipedia/commons/c/cd/AIIMS_-New_Delhi%27s_Ward_Block.jpg",
    content: `<h2>Medical Visa for India: Step-by-Step Guide</h2>
<p>India offers a dedicated Medical Visa (M-visa) for patients seeking treatment at recognized hospitals. This comprehensive guide explains the entire process.</p>
<h2>Eligibility</h2>
<p>A Medical Visa is available to foreign nationals seeking medical treatment at recognized/approved hospitals in India. The visa allows up to three accompanying family members on Medical Attendant Visas.</p>
<h2>Required Documents</h2>
<ul><li>Valid passport with at least 6 months validity</li><li>Medical certificate from a recognized hospital in the home country</li><li>Letter from the Indian hospital confirming treatment and timeline</li><li>Recent passport-size photographs</li><li>Proof of financial means to cover treatment costs</li></ul>
<h2>Application Process</h2>
<ol><li>Apply online through the Indian visa portal</li><li>Upload required documents</li><li>Pay visa fee (varies by nationality)</li><li>Schedule appointment at Indian embassy/consulate if required</li><li>Receive e-Medical Visa within 3-5 working days</li></ol>
<p>The e-Medical Visa is valid for 60 days with triple entry, extendable for up to one year while undergoing treatment.</p>`,
  },
];
