export const fallbackDoctors = [
  {
    name: "Dr. Rajesh Sharma",
    specialty: "Cardiac Surgery",
    specialties: ["Cardiac Surgery"],
    experience: "28 years",
    experience_years: 28,
    hospital: "AIIMS Delhi",
    rating: 4.9,
    slug: "dr-rajesh-sharma",
    photo_url: "/images/doctor-sharma.webp",
    qualifications: "MBBS, MS, MCh Cardiothoracic Surgery",
    about:
      "Senior cardiac surgeon at AIIMS with expertise in complex coronary bypass, valve repair, and paediatric cardiac surgery. Has performed over 10,000 cardiac procedures.",
  },
  {
    name: "Dr. Naresh Trehan",
    specialty: "Cardiac Surgery",
    specialties: ["Cardiac Surgery"],
    experience: "45 years",
    experience_years: 45,
    hospital: "Medanta - The Medicity",
    rating: 4.9,
    slug: "dr-naresh-trehan",
    photo_url: "/images/doctor-trehan.webp",
    qualifications: "MBBS, MD, FACS",
    about:
      "World-renowned cardiovascular surgeon and Chairman of Medanta. Recipient of Padma Shri and Dr. B. C. Roy Award. Pioneer in minimally invasive cardiac surgery in India.",
  },
  {
    name: "Dr. Priya Singh",
    specialty: "Neurology",
    specialties: ["Neurology"],
    experience: "18 years",
    experience_years: 18,
    hospital: "AIIMS Delhi",
    rating: 4.8,
    slug: "dr-priya-singh",
    photo_url: "/images/doctor-singh.webp",
    qualifications: "MBBS, MD Medicine, DM Neurology",
    about:
      "Consultant neurologist at AIIMS specializing in stroke care, movement disorders, epilepsy management, and neuro-immunology. Published over 40 research papers.",
  },
  {
    name: "Dr. Ashok Seth",
    specialty: "Cardiology",
    specialties: ["Cardiology"],
    experience: "40 years",
    experience_years: 40,
    hospital: "Fortis Escorts Heart Institute",
    rating: 4.9,
    slug: "dr-ashok-seth",
    photo_url: "/images/doctor-seth.webp",
    qualifications: "MBBS, MD, DM Cardiology, FACC",
    about:
      "Chairman of Cardiology at Fortis Escorts. Padma Shri awardee and pioneer of coronary angioplasty in India. Has performed over 35,000 coronary interventions.",
  },
  {
    name: "Dr. Arvind Kumar",
    specialty: "Oncology",
    specialties: ["Oncology"],
    experience: "32 years",
    experience_years: 32,
    hospital: "Medanta - The Medicity",
    rating: 4.9,
    slug: "dr-arvind-kumar",
    photo_url: "/images/doctor-kumar.webp",
    qualifications: "MBBS, MS, MCh Surgical Oncology",
    about:
      "Leading chest and thoracic oncology surgeon at Medanta. Pioneer of minimally invasive thoracic surgery in India. Expert in lung cancer and mediastinal tumor surgery.",
  },
  {
    name: "Dr. Atul Prasad",
    specialty: "Neurology",
    specialties: ["Neurology"],
    experience: "25 years",
    experience_years: 25,
    hospital: "Medanta - The Medicity",
    rating: 4.8,
    slug: "dr-atul-prasad",
    photo_url: "/images/doctor-prasad.webp",
    qualifications: "MBBS, MD Medicine, DM Neurology",
    about:
      "Principal Director of Neurology at Medanta. Specialist in stroke management, epilepsy surgery evaluation, and neurodegenerative disorders.",
  },
  {
    name: "Dr. Ishwar Bohra",
    specialty: "Orthopedics",
    specialties: ["Orthopedics"],
    experience: "22 years",
    experience_years: 22,
    hospital: "Medanta - The Medicity",
    rating: 4.8,
    slug: "dr-ishwar-bohra",
    photo_url: "/images/doctor-bohra.webp",
    qualifications: "MBBS, MS Orthopedics, FRCS",
    about:
      "Senior orthopedic surgeon at Medanta specializing in hip and knee replacement surgeries. Has performed over 8,000 joint replacement procedures.",
  },
  {
    name: "Dr. Subhash Gupta",
    specialty: "Transplant Surgery",
    specialties: ["Transplant", "Liver Surgery"],
    experience: "30 years",
    experience_years: 30,
    hospital: "Medanta - The Medicity",
    rating: 4.9,
    slug: "dr-subhash-gupta",
    photo_url: "/images/doctor-gupta.webp",
    qualifications: "MBBS, MS, FRCS",
    about:
      "Chairman of Liver Transplant & Biliary Sciences at Medanta. Has performed over 1,500 living donor liver transplants with success rates matching global standards.",
  },
  {
    name: "Dr. Anupam Saha",
    specialty: "Neurosurgery",
    specialties: ["Neurosurgery"],
    experience: "26 years",
    experience_years: 26,
    hospital: "Apollo Hospitals Delhi",
    rating: 4.8,
    slug: "dr-anupam-saha",
    photo_url: "/images/doctor-saha.webp",
    qualifications: "MBBS, MS, MCh Neurosurgery",
    about:
      "Senior neurosurgeon at Apollo Indraprastha specializing in brain tumor surgery, spine stabilization, and cerebrovascular interventions.",
  },
  {
    name: "Dr. Sandeep Vaishya",
    specialty: "Neurosurgery",
    specialties: ["Neurosurgery"],
    experience: "28 years",
    experience_years: 28,
    hospital: "Max Super Speciality Hospital Saket",
    rating: 4.8,
    slug: "dr-sandeep-vaishya",
    photo_url: "/images/doctor-vaishya.webp",
    qualifications: "MBBS, MS, MCh Neurosurgery",
    about:
      "Executive Director of Neurosurgery at Max Saket. Specialist in brain tumor surgery, deep brain stimulation, and complex spine surgery.",
  },
  {
    name: "Dr. Rashmi Taluja",
    specialty: "Fertility & IVF",
    specialties: ["Fertility", "IVF"],
    experience: "22 years",
    experience_years: 22,
    hospital: "Artemis Hospital Gurugram",
    rating: 4.8,
    slug: "dr-rashmi-taluja",
    photo_url: "/images/doctor-taluja.webp",
    qualifications: "MBBS, MS, FRCOG",
    about:
      "Senior IVF and fertility specialist at Artemis Hospital. Specialist in recurrent pregnancy loss, PCOS management, and advanced reproductive techniques including ICSI and egg donation.",
  },
  {
    name: "Dr. H.S. Chhabra",
    specialty: "Spine Surgery",
    specialties: ["Spine Surgery"],
    experience: "38 years",
    experience_years: 38,
    hospital: "Indian Spinal Injuries Centre",
    rating: 4.9,
    slug: "dr-hs-chhabra",
    photo_url: "/images/doctor-chhabra.webp",
    qualifications: "MBBS, MS Orthopedics, FICS",
    about:
      "Chief of Spine Services at Indian Spinal Injuries Centre. Pioneer of spine deformity correction and minimally invasive spine surgery in India. Awarded Padma Shri.",
  },
  {
    name: "Dr. Pradeep Sethi",
    specialty: "Paediatric Cardiac Surgery",
    specialties: ["Paediatric Cardiac Surgery"],
    experience: "28 years",
    experience_years: 28,
    hospital: "BLK-Max Super Speciality Hospital",
    rating: 4.9,
    slug: "dr-pradeep-sethi",
    photo_url: "/images/doctor-sethi.webp",
    qualifications: "MBBS, MS, MCh Cardiothoracic Surgery",
    about:
      "Vice Chairman of Paediatric Cardiac Surgery at BLK-Max. Has performed over 6,000 paediatric cardiac surgeries including complex neonatal heart defect repairs.",
  },
  {
    name: "Dr. Deepak K. Tempe",
    specialty: "Cardiology",
    specialties: ["Cardiology"],
    experience: "35 years",
    experience_years: 35,
    hospital: "Sir Ganga Ram Hospital",
    rating: 4.7,
    slug: "dr-deepak-tempe",
    photo_url: "/images/doctor-tempe.webp",
    qualifications: "MBBS, MD, DM Cardiology",
    about:
      "Senior cardiologist at Sir Ganga Ram Hospital with vast experience in interventional cardiology, coronary angioplasty, and pacemaker implantation.",
  },
  {
    name: "Dr. Raju Garg",
    specialty: "Orthopedics",
    specialties: ["Orthopedics"],
    experience: "22 years",
    experience_years: 22,
    hospital: "Apollo Hospitals Delhi",
    rating: 4.8,
    slug: "dr-raju-garg",
    photo_url: "/images/doctor-garg.webp",
    qualifications: "MBBS, MS Orthopedics, DNB",
    about:
      "Senior orthopedic surgeon at Apollo Indraprastha specializing in hip and knee replacement, arthroscopy, and sports injury management.",
  },
  {
    name: "Dr. Archana Verma",
    specialty: "Ophthalmology",
    specialties: ["Ophthalmology"],
    experience: "22 years",
    experience_years: 22,
    hospital: "Moolchand Hospital",
    rating: 4.7,
    slug: "dr-archana-verma",
    photo_url: "/images/doctor-verma.webp",
    qualifications: "MBBS, MS, FRCS Ophthalmology",
    about:
      "Senior ophthalmologist at Moolchand Hospital specializing in cataract surgery, retinal disorders, and LASIK procedures.",
  },
  {
    name: "Dr. Vivek Bansal",
    specialty: "Gastroenterology",
    specialties: ["Gastroenterology"],
    experience: "18 years",
    experience_years: 18,
    hospital: "Paras Hospital Gurugram",
    rating: 4.7,
    slug: "dr-vivek-bansal",
    photo_url: "/images/doctor-bansal.webp",
    qualifications: "MBBS, MD, DM Gastroenterology",
    about:
      "Gastroenterologist at Paras Hospital specializing in therapeutic endoscopy, liver disease management, and bariatric surgery support.",
  },
  {
    name: "Dr. Vikas Dua",
    specialty: "Hematology & BMT",
    specialties: ["Oncology", "Hematology"],
    experience: "20 years",
    experience_years: 20,
    hospital: "Max Super Speciality Hospital Saket",
    rating: 4.8,
    slug: "dr-vikas-dua",
    photo_url: "/images/doctor-dua.webp",
    qualifications: "MBBS, MD, DM Hematology",
    about:
      "Director of Paediatric Hematology & Bone Marrow Transplant at Max Saket. Has performed over 500 bone marrow transplants including haploidentical transplants.",
  },
  {
    name: "Dr. Yash Gulati",
    specialty: "Orthopedics",
    specialties: ["Orthopedics"],
    experience: "30 years",
    experience_years: 30,
    hospital: "BLK-Max Super Speciality Hospital",
    rating: 4.8,
    slug: "dr-yash-gulati",
    photo_url: "/images/doctor-gulati.webp",
    qualifications: "MBBS, MS Orthopedics, MCh Orthopedics",
    about:
      "Senior orthopedic surgeon at BLK-Max with expertise in joint replacement, arthroscopy, and sports medicine. Trained in leading orthopedic centres in the UK and Australia.",
  },
  {
    name: "Dr. Anil Arora",
    specialty: "Gastroenterology",
    specialties: ["Gastroenterology"],
    experience: "32 years",
    experience_years: 32,
    hospital: "Sir Ganga Ram Hospital",
    rating: 4.8,
    slug: "dr-anil-arora",
    photo_url: "/images/doctor-arora.webp",
    qualifications: "MBBS, MD, DM Gastroenterology",
    about:
      "Chairman of Gastroenterology at Sir Ganga Ram Hospital. Expert in therapeutic endoscopy, ERCP, and inflammatory bowel disease management.",
  },
  {
    name: "Dr. Vivek Vij",
    specialty: "Liver Transplant",
    specialties: ["Transplant", "Liver Surgery"],
    experience: "24 years",
    experience_years: 24,
    hospital: "Fortis Memorial Research Institute",
    rating: 4.9,
    slug: "dr-vivek-vij",
    photo_url: "/images/doctor-vij.webp",
    qualifications: "MBBS, MS, FRCS",
    about:
      "Director of Liver Transplant at Fortis FMRI. Has performed over 1,000 liver transplants. Pioneer in ABO-incompatible liver transplantation in India.",
  },
  {
    name: "Dr. Manoj Miglani",
    specialty: "Orthopedics",
    specialties: ["Orthopedics"],
    experience: "25 years",
    experience_years: 25,
    hospital: "Artemis Hospital Gurugram",
    rating: 4.7,
    slug: "dr-manoj-miglani",
    photo_url: "/images/doctor-miglani.webp",
    qualifications: "MBBS, MS Orthopedics, FRCS",
    about:
      "Senior orthopedic surgeon at Artemis Hospital specializing in joint replacement, arthroscopic surgery, and complex trauma reconstruction.",
  },
  {
    name: "Dr. D.S. Rana",
    specialty: "Nephrology",
    specialties: ["Nephrology"],
    experience: "34 years",
    experience_years: 34,
    hospital: "Sir Ganga Ram Hospital",
    rating: 4.8,
    slug: "dr-ds-rana",
    photo_url: "/images/doctor-rana.webp",
    qualifications: "MBBS, MD, DM Nephrology",
    about:
      "Chairman of Nephrology at Sir Ganga Ram Hospital. Expert in kidney transplant, dialysis management, and chronic kidney disease care.",
  },
  {
    name: "Dr. Z S Meharwal",
    specialty: "Cardiac Surgery",
    specialties: ["Cardiac Surgery"],
    experience: "32 years",
    experience_years: 32,
    hospital: "Fortis Escorts Heart Institute",
    rating: 4.8,
    slug: "dr-zs-meharwal",
    photo_url: "/images/doctor-meharwal.webp",
    qualifications: "MBBS, MS, MCh Cardiothoracic Surgery",
    about:
      "Senior cardiac surgeon at Fortis Escorts specializing in beating heart bypass surgery, valve repair, and aortic surgery.",
  },
  {
    name: "Dr. Atul Aggarwal",
    specialty: "Neurology",
    specialties: ["Neurology"],
    experience: "24 years",
    experience_years: 24,
    hospital: "Max Super Speciality Hospital Saket",
    rating: 4.8,
    slug: "dr-atul-aggarwal",
    photo_url: "/images/doctor-aggarwal.webp",
    qualifications: "MBBS, MD, DM Neurology",
    about:
      "Senior neurologist at Max Saket specializing in stroke management, epilepsy, Parkinson's disease, and dementia care.",
  },
  {
    name: "Dr. Sameer Kaushal",
    specialty: "Cardiology",
    specialties: ["Cardiology"],
    experience: "24 years",
    experience_years: 24,
    hospital: "Manipal Hospital Dwarka",
    rating: 4.7,
    slug: "dr-sameer-kaushal",
    photo_url: "/images/doctor-kaushal.webp",
    qualifications: "MBBS, MD, DM Cardiology",
    about:
      "Senior cardiologist at Manipal Hospital Dwarka specializing in coronary interventions, echocardiography, and preventive cardiology.",
  },
  {
    name: "Dr. Rakesh Gupta",
    specialty: "Cardiology",
    specialties: ["Cardiology"],
    experience: "27 years",
    experience_years: 27,
    hospital: "Artemis Hospital Gurugram",
    rating: 4.7,
    slug: "dr-rakesh-gupta",
    photo_url: "/images/doctor-gupta2.webp",
    qualifications: "MBBS, MD, DM Cardiology",
    about:
      "Senior interventional cardiologist at Artemis Hospital specializing in complex coronary interventions, peripheral angioplasty, and structural heart disease treatment.",
  },
  {
    name: "Dr. Simmardeep Gill",
    specialty: "Neurology",
    specialties: ["Neurology"],
    experience: "20 years",
    experience_years: 20,
    hospital: "Fortis Memorial Research Institute",
    rating: 4.7,
    slug: "dr-simmardeep-gill",
    photo_url: "/images/doctor-gill.webp",
    qualifications: "MBBS, MD, DM Neurology",
    about:
      "Neurologist at Fortis FMRI specializing in stroke interventions, neurocritical care, and multiple sclerosis management.",
  },
  {
    name: "Dr. Sushant Srivastava",
    specialty: "Urology",
    specialties: ["Urology"],
    experience: "18 years",
    experience_years: 18,
    hospital: "Apollo Hospitals Delhi",
    rating: 4.7,
    slug: "dr-sushant-srivastava",
    photo_url: "/images/doctor-srivastava.webp",
    qualifications: "MBBS, MS, MCh Urology",
    about:
      "Urologist at Apollo Indraprastha specializing in robotic prostate surgery, kidney stone treatment, and uro-oncology.",
  },
  {
    name: "Dr. Aditi Sharma",
    specialty: "Fertility & IVF",
    specialties: ["Fertility", "IVF"],
    experience: "16 years",
    experience_years: 16,
    hospital: "BLK-Max Super Speciality Hospital",
    rating: 4.7,
    slug: "dr-aditi-sharma",
    photo_url: "/images/doctor-sharma2.webp",
    qualifications: "MBBS, MD, DNB Obstetrics & Gynecology",
    about:
      "Fertility specialist at BLK-Max with expertise in IVF, ICSI, fertility preservation, and reproductive endocrinology.",
  },
  {
    name: "Dr. Anurag Saxena",
    specialty: "Oncology",
    specialties: ["Oncology"],
    experience: "22 years",
    experience_years: 22,
    hospital: "Fortis Memorial Research Institute",
    rating: 4.8,
    slug: "dr-anurag-saxena",
    photo_url: "/images/doctor-saxena.webp",
    qualifications: "MBBS, MD, DM Medical Oncology",
    about:
      "Senior medical oncologist at Fortis FMRI specializing in breast cancer, lung cancer, and hematological malignancies. Expert in targeted therapy and immunotherapy.",
  },
  {
    name: "Dr. Vivek Loomba",
    specialty: "Orthopedics",
    specialties: ["Orthopedics"],
    experience: "20 years",
    experience_years: 20,
    hospital: "Manipal Hospital Dwarka",
    rating: 4.6,
    slug: "dr-vivek-loomba",
    photo_url: "/images/doctor-loomba.webp",
    qualifications: "MBBS, MS Orthopedics",
    about:
      "Orthopedic surgeon at Manipal Hospital Dwarka specializing in joint replacement, arthroscopy, and trauma surgery.",
  },
  {
    name: "Dr. Rajendra Kumar",
    specialty: "Cardiology",
    specialties: ["Cardiology"],
    experience: "26 years",
    experience_years: 26,
    hospital: "Narayana Superspeciality Hospital Gurugram",
    rating: 4.7,
    slug: "dr-rajendra-kumar",
    photo_url: "/images/doctor-rajendra-kumar.webp",
    qualifications: "MBBS, MD, DM Cardiology",
    about:
      "Senior cardiologist at Narayana Superspeciality Hospital Gurugram specializing in high-volume coronary interventions and heart failure management.",
  },
  {
    name: "Dr. Alok Gupta",
    specialty: "Orthopedics",
    specialties: ["Orthopedics"],
    experience: "20 years",
    experience_years: 20,
    hospital: "Columbia Asia Hospital Gurugram",
    rating: 4.6,
    slug: "dr-alok-gupta",
    photo_url: "/images/doctor-alok-gupta.webp",
    qualifications: "MBBS, MS Orthopedics",
    about:
      "Orthopedic surgeon at Columbia Asia Hospital Gurugram specializing in joint replacement, arthroscopy, and sports injuries.",
  },
  {
    name: "Dr. Amit Kumar",
    specialty: "Orthopedics",
    specialties: ["Orthopedics"],
    experience: "20 years",
    experience_years: 20,
    hospital: "AIIMS Delhi",
    rating: 4.7,
    slug: "dr-amit-kumar",
    photo_url: "/images/doctor-amit-kumar.webp",
    qualifications: "MBBS, MS Orthopedics",
    about:
      "Orthopedic surgeon at AIIMS specializing in joint replacement, spine surgery, and trauma management.",
  },
];

export const fallbackHospitals = [
  {
    name: "All India Institute of Medical Sciences (AIIMS)",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "2,478+",
    beds_count: 2478,
    accreditation: "NABH, Govt of India",
    accreditations: ["NABH", "Govt of India"],
    slug: "aiims-delhi",
    photo_url: "/images/hospital-aiims.webp",
    about:
      "AIIMS is India's premier medical institution and hospital, renowned for its high-quality patient care, medical education, and research. With over 2,400 beds and 600+ specialists, it offers comprehensive treatment across all major specialties at highly affordable rates.",
  },
  {
    name: "Medanta - The Medicity",
    location: "Gurugram, Haryana",
    city: "Gurugram",
    state: "Haryana",
    beds: "1,250+",
    beds_count: 1250,
    accreditation: "JCI, NABH",
    accreditations: ["JCI", "NABH"],
    slug: "medanta-the-medicity",
    photo_url: "/images/hospital-medanta.webp",
    about:
      "Medanta is one of India's largest multi-specialty hospitals with a dedicated international patient wing. It features 45+ operating theatres, advanced robotic surgery systems, and world-renowned cardiac, oncology, transplant, and orthopaedic programs.",
  },
  {
    name: "Apollo Hospitals Indraprastha",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "700+",
    beds_count: 700,
    accreditation: "JCI, NABH",
    accreditations: ["JCI", "NABH"],
    slug: "apollo-hospitals-delhi",
    photo_url: "/images/hospital-apollo.webp",
    about:
      "Apollo Hospitals Indraprastha is a flagship tertiary care hospital in South East Asia with internationally accredited programs in cardiac sciences, oncology, neurosciences, orthopedics, and organ transplantation.",
  },
  {
    name: "Fortis Escorts Heart Institute",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "485+",
    beds_count: 485,
    accreditation: "JCI, NABH",
    accreditations: ["JCI", "NABH"],
    slug: "fortis-escorts-heart-institute",
    photo_url: "/images/hospital-fortis-escorts.webp",
    about:
      "Fortis Escorts Heart Institute is India's most recognised cardiac care hospital, performing over 15,000 cardiac surgeries annually with world-class success rates.",
  },
  {
    name: "Max Super Speciality Hospital Saket",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "680+",
    beds_count: 680,
    accreditation: "JCI, NABH",
    accreditations: ["JCI", "NABH"],
    slug: "max-super-speciality-hospital-saket",
    photo_url: "/images/hospital-max-saket.webp",
    about:
      "Max Super Speciality Hospital Saket is a multi-specialty tertiary care hospital known for its advanced neurosciences, bone marrow transplant program, cardiac care, and oncology services.",
  },
  {
    name: "Sir Ganga Ram Hospital",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "650+",
    beds_count: 650,
    accreditation: "NABH, ISO 9001",
    accreditations: ["NABH", "ISO 9001"],
    slug: "sir-ganga-ram-hospital",
    photo_url: "/images/hospital-ganga-ram.webp",
    about:
      "Sir Ganga Ram Hospital is a premier multi-specialty hospital in New Delhi with a 70-year legacy of medical excellence across cardiology, gastroenterology, nephrology, and urology.",
  },
  {
    name: "BLK-Max Super Speciality Hospital",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "650+",
    beds_count: 650,
    accreditation: "JCI, NABH",
    accreditations: ["JCI", "NABH"],
    slug: "blk-max-super-speciality-hospital",
    photo_url: "/images/hospital-blk.webp",
    about:
      "BLK-Max Super Speciality Hospital is a leading healthcare facility in Central Delhi with 650 beds and 17 super-speciality departments, renowned for paediatric cardiac surgery, orthopedics, and fertility treatment.",
  },
  {
    name: "Artemis Hospital Gurugram",
    location: "Gurugram, Haryana",
    city: "Gurugram",
    state: "Haryana",
    beds: "500+",
    beds_count: 500,
    accreditation: "JCI, NABH",
    accreditations: ["JCI", "NABH"],
    slug: "artemis-hospital-gurugram",
    photo_url: "/images/hospital-artemis.webp",
    about:
      "Artemis Hospital is a state-of-the-art multi-specialty hospital in Gurugram with JCI accreditation, offering advanced care in cardiology, orthopedics, IVF, and oncology with a focus on medical tourism.",
  },
  {
    name: "Fortis Memorial Research Institute",
    location: "Gurugram, Haryana",
    city: "Gurugram",
    state: "Haryana",
    beds: "1,000+",
    beds_count: 1000,
    accreditation: "JCI, NABH",
    accreditations: ["JCI", "NABH"],
    slug: "fortis-memorial-research-institute",
    photo_url: "/images/hospital-fmri.webp",
    about:
      "Fortis Memorial Research Institute (FMRI) is a flagship quaternary care hospital with dedicated centres for oncology, neurosciences, orthopedics, cardiac care, and liver transplant.",
  },
  {
    name: "Manipal Hospital Dwarka",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "380+",
    beds_count: 380,
    accreditation: "NABH, ISO 9001",
    accreditations: ["NABH", "ISO 9001"],
    slug: "manipal-hospital-dwarka",
    photo_url: "/images/hospital-manipal.webp",
    about:
      "Manipal Hospital Dwarka is a multi-specialty tertiary care hospital serving West Delhi with comprehensive healthcare services including cardiology, orthopedics, neurology, and gastroenterology.",
  },
  {
    name: "Indian Spinal Injuries Centre",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "250+",
    beds_count: 250,
    accreditation: "NABH, ISO 9001",
    accreditations: ["NABH", "ISO 9001"],
    slug: "indian-spinal-injuries-centre",
    photo_url: "/images/hospital-spinal.webp",
    about:
      "The Indian Spinal Injuries Centre is Asia's premier institute for spine care and rehabilitation, offering comprehensive treatment for spinal trauma, degenerative spine conditions, and sports injuries.",
  },
  {
    name: "Venkateshwar Hospital",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "350+",
    beds_count: 350,
    accreditation: "NABH",
    accreditations: ["NABH"],
    slug: "venkateshwar-hospital",
    photo_url: "/images/hospital-venkateshwar.webp",
    about:
      "Venkateshwar Hospital is a multi-super-speciality hospital in Dwarka offering advanced medical care in gastroenterology, cardiology, orthopedics, nephrology, and general surgery.",
  },
  {
    name: "Saroj Super Speciality Hospital",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "300+",
    beds_count: 300,
    accreditation: "NABH",
    accreditations: ["NABH"],
    slug: "saroj-super-speciality-hospital",
    photo_url: "/images/hospital-saroj.webp",
    about:
      "Saroj Super Speciality Hospital is a well-established medical facility in Central Delhi known for its urology, nephrology, and general surgery departments at affordable prices.",
  },
  {
    name: "Paras Hospital Gurugram",
    location: "Gurugram, Haryana",
    city: "Gurugram",
    state: "Haryana",
    beds: "350+",
    beds_count: 350,
    accreditation: "NABH, ISO 9001",
    accreditations: ["NABH", "ISO 9001"],
    slug: "paras-hospital-gurugram",
    photo_url: "/images/hospital-paras.webp",
    about:
      "Paras Hospital is a multi-specialty tertiary care hospital in Gurugram with expertise in gastroenterology, bariatric surgery, orthopedics, and fertility treatment.",
  },
  {
    name: "Narayana Superspeciality Hospital Gurugram",
    location: "Gurugram, Haryana",
    city: "Gurugram",
    state: "Haryana",
    beds: "450+",
    beds_count: 450,
    accreditation: "NABH, ISO 9001",
    accreditations: ["NABH", "ISO 9001"],
    slug: "narayana-superspeciality-hospital-gurugram",
    photo_url: "/images/hospital-narayana.webp",
    about:
      "Narayana Superspeciality Hospital is part of the renowned Narayana Health chain, offering affordable cardiac care, oncology, orthopedics, and neurosurgery with outcomes matching global benchmarks.",
  },
  {
    name: "Moolchand Hospital",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    beds: "325+",
    beds_count: 325,
    accreditation: "NABH, ISO 9001",
    accreditations: ["NABH", "ISO 9001"],
    slug: "moolchand-hospital",
    photo_url: "/images/hospital-moolchand.webp",
    about:
      "Moolchand Hospital is a 325-bed multi-specialty hospital in South Delhi with a 70-year legacy, offering comprehensive care in ophthalmology, orthopedics, cardiology, and women's health.",
  },
  {
    name: "Columbia Asia Hospital Gurugram",
    location: "Gurugram, Haryana",
    city: "Gurugram",
    state: "Haryana",
    beds: "200+",
    beds_count: 200,
    accreditation: "JCI, NABH",
    accreditations: ["JCI", "NABH"],
    slug: "columbia-asia-hospital-gurugram",
    photo_url: "/images/hospital-columbia.webp",
    about:
      "Columbia Asia Hospital is a JCI-accredited tertiary care facility in Gurugram offering comprehensive services in orthopedics, cardiology, and general surgery.",
  },
];

export const fallbackTreatments = [
  {
    name: "Knee Replacement",
    costMin: 6500,
    costMax: 8500,
    usCost: 45000,
    slug: "knee-replacement",
    category: "Orthopedics",
    description:
      "Total and partial knee replacement options with leading orthopedic surgeons, modern implants, physiotherapy, and recovery support.",
  },
  {
    name: "Hip Replacement",
    costMin: 7000,
    costMax: 9500,
    usCost: 50000,
    slug: "hip-replacement",
    category: "Orthopedics",
    description:
      "Hip replacement surgery packages covering pre-surgery evaluation, implant selection, hospital stay, and rehabilitation guidance.",
  },
  {
    name: "Spine Surgery",
    costMin: 8000,
    costMax: 12000,
    usCost: 65000,
    slug: "spine-surgery",
    category: "Neurology",
    description:
      "Advanced spine surgery options for disc, deformity, and nerve compression conditions with multidisciplinary care planning.",
  },
  {
    name: "Hair Transplant",
    costMin: 2000,
    costMax: 4000,
    usCost: 15000,
    slug: "hair-transplant",
    category: "Cosmetic",
    description:
      "FUE and FUT hair restoration options with transparent graft planning, procedure-day support, and post-treatment care instructions.",
  },
  {
    name: "IVF Treatment",
    costMin: 3000,
    costMax: 6000,
    usCost: 20000,
    slug: "ivf-treatment",
    category: "Fertility",
    description:
      "Fertility treatment coordination including IVF cycles, diagnostics, embryo transfer, and specialist follow-up.",
  },
  {
    name: "Bariatric Surgery",
    costMin: 5000,
    costMax: 7500,
    usCost: 25000,
    slug: "bariatric-surgery",
    category: "Gastroenterology",
    description:
      "Weight-loss surgery options including gastric sleeve and bypass with diet planning, pre-op checks, and recovery guidance.",
  },
  {
    name: "Heart Bypass Surgery",
    costMin: 7000,
    costMax: 10000,
    usCost: 100000,
    slug: "heart-bypass-surgery",
    category: "Cardiology",
    description:
      "CABG treatment planning with cardiac surgeon opinions, pre-operative evaluation, ICU stay guidance, and rehabilitation support.",
  },
  {
    name: "Angioplasty",
    costMin: 3500,
    costMax: 6500,
    usCost: 30000,
    slug: "angioplasty",
    category: "Cardiology",
    description:
      "Coronary angioplasty and stent options with transparent device-cost discussion and cardiology follow-up planning.",
  },
  {
    name: "Bone Marrow Transplant",
    costMin: 18000,
    costMax: 35000,
    usCost: 250000,
    slug: "bone-marrow-transplant",
    category: "Oncology",
    description:
      "Transplant evaluation coordination for hematology patients, including donor planning, hospital stay expectations, and infection-safety guidance.",
  },
  {
    name: "Liver Transplant",
    costMin: 28000,
    costMax: 45000,
    usCost: 350000,
    slug: "liver-transplant",
    category: "Transplant",
    description:
      "Liver transplant opinion and hospital coordination for eligible patients, with donor evaluation and extended-stay planning.",
  },
  {
    name: "Kidney Transplant",
    costMin: 14000,
    costMax: 22000,
    usCost: 250000,
    slug: "kidney-transplant",
    category: "Transplant",
    description:
      "Kidney transplant coordination including nephrology review, donor compatibility guidance, hospital admission, and post-transplant follow-up.",
  },
  {
    name: "Dental Implants",
    costMin: 800,
    costMax: 3000,
    usCost: 12000,
    slug: "dental-implants",
    category: "Dental",
    description:
      "Single and full-mouth implant treatment planning with dental imaging, implant-system choices, and staged-visit coordination.",
  },
  {
    name: "Robotic Prostate Surgery",
    costMin: 6500,
    costMax: 9500,
    usCost: 55000,
    slug: "robotic-prostate-surgery",
    category: "Urology",
    description:
      "Robotic urology surgery options with specialist review, diagnostic workup coordination, and recovery-stay support.",
  },
  {
    name: "Cataract Surgery",
    costMin: 900,
    costMax: 2500,
    usCost: 7000,
    slug: "cataract-surgery",
    category: "Ophthalmology",
    description:
      "Cataract treatment coordination with lens-option discussion, day-care procedure planning, and follow-up appointment support.",
  },
];

export const fallbackTestimonials = [
  {
    name: "Grace Mwangi",
    country: "Kenya",
    treatment: "Knee Replacement",
    text:
      "I had been suffering from knee pain for years. Asians Healthcare made everything easy - from my visa to hospital stay. The doctors were exceptional.",
    rating: 5,
    videoId: "oB2GzmHqVBM",
  },
  {
    name: "Ahmed Al-Rashid",
    country: "Iraq",
    treatment: "Liver Transplant",
    text:
      "Finding a reliable medical tourism facilitator was my biggest concern. Asians Healthcare exceeded all expectations and coordinated everything perfectly.",
    rating: 5,
    videoId: "3rUulNKF26s",
  },
  {
    name: "Fatima Okafor",
    country: "Nigeria",
    treatment: "IVF Treatment",
    text:
      "After years of trying, Asians Healthcare helped us start our family. The entire team was supportive and professional.",
    rating: 5,
    videoId: "O-Dp9aHZldA",
  },
  {
    name: "James Mwangi",
    country: "Kenya",
    treatment: "Cardiac Bypass",
    text:
      "My heart surgery at Medanta was life-changing. The coordination by Asians Healthcare was flawless from Nairobi to Delhi and back.",
    rating: 5,
    videoId: "",
  },
  {
    name: "Raj Patel",
    country: "United Kingdom",
    treatment: "Hip Replacement",
    text:
      "The cost savings were substantial but the quality of care was world-class. I would recommend Asians Healthcare to anyone considering treatment in India.",
    rating: 5,
    videoId: "",
  },
  {
    name: "Nadia Khan",
    country: "Bangladesh",
    treatment: "Kidney Transplant",
    text:
      "My brother received a life-saving kidney transplant through Asians Healthcare. The coordination, hospital selection, and follow-up were outstanding.",
    rating: 5,
    videoId: "",
  },
];

export const fallbackInsurances = [
  "AAR Insurance Africa",
  "Allianz Care",
  "Britam Health Insurance",
  "Bupa Global",
  "Cigna Global",
  "Jubilee Insurance",
  "SHA Kenya",
  "UAP Old Mutual Insurance",
];

export const fallbackHotels = [
  {
    name: "The Medicity Suites",
    address: "Sector 38, Gurugram",
    stars: 4,
    price: "$$$",
    near: "Medanta - The Medicity",
  },
  {
    name: "Delhi Care Residency",
    address: "Sarita Vihar, New Delhi",
    stars: 3,
    price: "$$",
    near: "Apollo Hospitals Delhi",
  },
  {
    name: "FMRI Patient Apartments",
    address: "Sector 44, Gurugram",
    stars: 4,
    price: "$$$",
    near: "Fortis Memorial Research Institute",
  },
  {
    name: "AIIMS Patient Lodge",
    address: "Ansari Nagar, New Delhi",
    stars: 2,
    price: "$",
    near: "All India Institute of Medical Sciences (AIIMS)",
  },
  {
    name: "Fortis Escorts Guest House",
    address: "Okhla Road, New Delhi",
    stars: 3,
    price: "$$",
    near: "Fortis Escorts Heart Institute",
  },
  {
    name: "Max Saket International Stay",
    address: "Saket, New Delhi",
    stars: 4,
    price: "$$$",
    near: "Max Super Speciality Hospital Saket",
  },
  {
    name: "BLK Patient Comfort Inn",
    address: "Pusa Road, New Delhi",
    stars: 3,
    price: "$$",
    near: "BLK-Max Super Speciality Hospital",
  },
  {
    name: "Artemis Recovery Residency",
    address: "Sector 51, Gurugram",
    stars: 4,
    price: "$$$",
    near: "Artemis Hospital Gurugram",
  },
  {
    name: "Sir Ganga Ram Guest Rooms",
    address: "Rajendra Place, New Delhi",
    stars: 3,
    price: "$$",
    near: "Sir Ganga Ram Hospital",
  },
  {
    name: "Dwarka Medistay",
    address: "Sector 12, Dwarka, New Delhi",
    stars: 3,
    price: "$$",
    near: "Manipal Hospital Dwarka",
  },
];

export const fallbackSpecialties = [
  {
    name: "Cardiology",
    slug: "cardiology",
    desc: "Heart care, bypass surgery, valve replacement, angioplasty, and cardiac rehabilitation.",
  },
  {
    name: "Orthopedics",
    slug: "orthopedics",
    desc: "Joint replacement, spine care, sports injury treatment, and fracture management.",
  },
  {
    name: "Neurology",
    slug: "neurology",
    desc: "Stroke care, spine disorders, movement disorders, epilepsy, and neurosurgery coordination.",
  },
  {
    name: "Oncology",
    slug: "oncology",
    desc: "Cancer diagnosis, chemotherapy, radiation therapy, surgical oncology, and second opinions.",
  },
  {
    name: "Gastroenterology",
    slug: "gastroenterology",
    desc: "Digestive health, liver care, bariatric surgery, endoscopy, and transplant evaluation.",
  },
  {
    name: "Nephrology",
    slug: "nephrology",
    desc: "Kidney disease care, dialysis planning, transplant evaluation, and post-treatment support.",
  },
  {
    name: "Urology",
    slug: "urology",
    desc: "Kidney stones, prostate care, robotic urology surgery, and male reproductive health.",
  },
  {
    name: "Fertility",
    slug: "fertility",
    desc: "IVF, ICSI, fertility diagnostics, embryo transfer, and reproductive medicine coordination.",
  },
  {
    name: "Transplant",
    slug: "transplant",
    desc: "Kidney, liver, and bone marrow transplant evaluation with long-stay support planning.",
  },
  {
    name: "Dental",
    slug: "dental",
    desc: "Dental implants, smile design, oral surgery, and staged treatment planning for visitors.",
  },
  {
    name: "Ophthalmology",
    slug: "ophthalmology",
    desc: "Cataract, retina, LASIK, glaucoma, and advanced eye-care procedures.",
  },
  {
    name: "Cosmetic Surgery",
    slug: "cosmetic-surgery",
    desc: "Aesthetic and reconstructive procedures with privacy-focused recovery planning.",
  },
];
